package org.broadinstitute.gpinformatics.infrastructure.bsp.plating;

import java.util.List;

public class BSPPlatingRequestResult {

    /**
     * The barcode of the created plating request, if any
     */
    private String platingRequestReceipt;

    /**
     * Was the plating request submitted? If there were errors the answer will
     * definitely be no.
     */
    private boolean platingRequestSubmitted;

    /**
     * List of error messages generated by BSP. If there is anything here there
     * will be no work request barcode and the work request will not be
     * submitted.
     */
    private List<String> errors;

    /**
     * While potentially still significant, warnings will not prevent a plating
     * work request from being automatically submitted.
     */
    private List<String> warnings;

    /**
     * Informational messages that should still be shown on the Squid UI, but
     * should not be of serious concern.
     */
    private List<String> infos;


    public String getPlatingRequestReceipt() {
        return this.platingRequestReceipt;
    }

    public void setPlatingRequestReceipt(String barcode) {
        this.platingRequestReceipt = barcode;

    }

    public List<String> getErrors() {
        return errors;
    }

    public void setErrors(List<String> errors) {
        this.errors = errors;
    }

    public List<String> getWarnings() {
        return warnings;
    }

    public void setWarnings(List<String> warnings) {
        this.warnings = warnings;
    }

    public boolean isPlatingRequestSubmitted() {
        return platingRequestSubmitted;
    }

    public void setPlatingRequestSubmitted(boolean submitted) {
        this.platingRequestSubmitted = submitted;
    }

    public List<String> getInfos() {
        return infos;
    }

    public void setInfos(List<String> infos) {
        this.infos = infos;
    }

}
