LOAD DATA
APPEND INTO TABLE mapping_run_metrics
FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  run_name,
  run_date DATE "YYYYMMDDHH24MISS",
  analysis_name,
  analysis_node,
  dragen_version,
  total_input_reads,
  num_dup_marked_reads,
  num_dup_marked_removed,
  num_unique_reads,
  num_reads_mate_sequenced,
  num_reads_wo_mate_sequenced,
  num_qc_failed_reads,
  num_mapped_reads,
  num_unq_mapped_reads,
  num_unmapped_reads,
  num_singleton_reads,
  num_paired_reads,
  num_properly_paired_reads,
  num_not_properly_paired_reads,
  mapq_40_inf,
  mapq_30_40,
  mapq_20_30,
  mapq_10_20,
  mapq_0_10,
  mapq_na,
  reads_indel_r1,
  reads_indel_r2,
  soft_clipped_bases_r1,
  soft_clipped_bases_r2,
  total_alignments,
  secondary_alignments,
  supplementary_alignments,
  est_read_length,
  bases_in_ref_genome,
  bases_in_target_bed,
  avg_seq_coverage,
  avg_alignment_coverage,
  pct_coverage_100x_inf,
  pct_coverage_50x_100x,
  pct_coverage_20x_50x,
  pct_coverage_10x_20x,
  pct_coverage_3x_10x,
  pct_coverage_0x_3x,
  avg_x_chr_coverage,
  avg_y_chr_coverage,
  avg_mito_coverage,
  avg_autosomal_coverage,
  median_autosomal_coverage,
  mean_median_autosomal_coverage,
  x_y_avg_coverage_ratio,
  x_autosomal_avg_coverage_ratio,
  y_autosomal_avg_coverage_ratio,
  provided_sex_chr_ploidy,
  predicted_sex_chr_ploidy,
  capture_spec_target_region,
  est_sample_contamination,
  dragen_mapping_rate,
  mapping_run_metric_id "SEQ_MAP_RUN_METRIC.NEXTVAL"
)