//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.27 at 12:21:41 PM EST 
//


package org.broadinstitute.gpinformatics.mercury.boundary.run;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * This was originally generated from an XSD imported from Squid, but the generated code didn't work with RESTEasy,
 * so it had to be modified and saved.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "solexaRunLaneSynopsisBean"
})
@XmlRootElement(name = "SolexaRunSynopsisBean")
public class SolexaRunSynopsisBean {

    @XmlElement(name = "solexaRunLaneSynopsisBean")
    protected List<SolexaRunSynopsisBean.SolexaRunLaneSynopsisBean> solexaRunLaneSynopsisBean;
    @XmlAttribute(name = "runName")
    protected String runName;
    @XmlAttribute(name = "runBarcode")
    protected String runBarcode;
    @XmlAttribute(name = "actualReadStructure")
    protected String actualReadStructure;
    @XmlAttribute(name = "setupReadStructure")
    protected String setupReadStructure;
    @XmlAttribute(name = "imagedAreaPerLaneMM2")
    protected Double imagedAreaPerLaneMM2;
    @XmlAttribute(name = "lanesSequenced")
    protected String lanesSequenced;

    /**
     * Gets the value of the solexaRunLaneSynopsisBean property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the solexaRunLaneSynopsisBean property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSolexaRunLaneSynopsisBean().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SolexaRunSynopsisBean.SolexaRunLaneSynopsisBean }
     *
     *
     */
    public List<SolexaRunSynopsisBean.SolexaRunLaneSynopsisBean> getSolexaRunLaneSynopsisBean() {
        if (solexaRunLaneSynopsisBean == null) {
            solexaRunLaneSynopsisBean = new ArrayList<SolexaRunSynopsisBean.SolexaRunLaneSynopsisBean>();
        }
        return this.solexaRunLaneSynopsisBean;
    }

    /**
     * Gets the value of the runName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunName() {
        return runName;
    }

    /**
     * Sets the value of the runName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunName(String value) {
        this.runName = value;
    }

    /**
     * Gets the value of the runBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunBarcode() {
        return runBarcode;
    }

    /**
     * Sets the value of the runBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunBarcode(String value) {
        this.runBarcode = value;
    }

    /**
     * Gets the value of the actualReadStructure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualReadStructure() {
        return actualReadStructure;
    }

    /**
     * Sets the value of the actualReadStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualReadStructure(String value) {
        this.actualReadStructure = value;
    }

    /**
     * Gets the value of the setupReadStructure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetupReadStructure() {
        return setupReadStructure;
    }

    /**
     * Sets the value of the setupReadStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetupReadStructure(String value) {
        this.setupReadStructure = value;
    }

    /**
     * Gets the value of the imagedAreaPerLaneMM2 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getImagedAreaPerLaneMM2() {
        return imagedAreaPerLaneMM2;
    }

    /**
     * Sets the value of the imagedAreaPerLaneMM2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setImagedAreaPerLaneMM2(Double value) {
        this.imagedAreaPerLaneMM2 = value;
    }

    /**
     * Gets the value of the lanesSequenced property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanesSequenced() {
        return lanesSequenced;
    }

    /**
     * Sets the value of the lanesSequenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanesSequenced(String value) {
        this.lanesSequenced = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="laneNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="actualReadStructure" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SolexaRunLaneSynopsisBean {

        @XmlAttribute(name = "laneNumber", required = true)
        protected int laneNumber;
        @XmlAttribute(name = "actualReadStructure")
        protected String actualReadStructure;

        /**
         * Gets the value of the laneNumber property.
         * 
         */
        public int getLaneNumber() {
            return laneNumber;
        }

        /**
         * Sets the value of the laneNumber property.
         * 
         */
        public void setLaneNumber(int value) {
            this.laneNumber = value;
        }

        /**
         * Gets the value of the actualReadStructure property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActualReadStructure() {
            return actualReadStructure;
        }

        /**
         * Sets the value of the actualReadStructure property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActualReadStructure(String value) {
            this.actualReadStructure = value;
        }

    }

}
