package org.broadinstitute.gpinformatics.mercury.entity.vessel;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * A section is typically a set of wells in a plate, or positions in a rack.
 */
public enum SBSSection {
    // An entire 96-well plate.
    ALL96("ALL96", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A02,
            VesselPosition.A03,
            VesselPosition.A04,
            VesselPosition.A05,
            VesselPosition.A06,
            VesselPosition.A07,
            VesselPosition.A08,
            VesselPosition.A09,
            VesselPosition.A10,
            VesselPosition.A11,
            VesselPosition.A12,
            VesselPosition.B01,
            VesselPosition.B02,
            VesselPosition.B03,
            VesselPosition.B04,
            VesselPosition.B05,
            VesselPosition.B06,
            VesselPosition.B07,
            VesselPosition.B08,
            VesselPosition.B09,
            VesselPosition.B10,
            VesselPosition.B11,
            VesselPosition.B12,
            VesselPosition.C01,
            VesselPosition.C02,
            VesselPosition.C03,
            VesselPosition.C04,
            VesselPosition.C05,
            VesselPosition.C06,
            VesselPosition.C07,
            VesselPosition.C08,
            VesselPosition.C09,
            VesselPosition.C10,
            VesselPosition.C11,
            VesselPosition.C12,
            VesselPosition.D01,
            VesselPosition.D02,
            VesselPosition.D03,
            VesselPosition.D04,
            VesselPosition.D05,
            VesselPosition.D06,
            VesselPosition.D07,
            VesselPosition.D08,
            VesselPosition.D09,
            VesselPosition.D10,
            VesselPosition.D11,
            VesselPosition.D12,
            VesselPosition.E01,
            VesselPosition.E02,
            VesselPosition.E03,
            VesselPosition.E04,
            VesselPosition.E05,
            VesselPosition.E06,
            VesselPosition.E07,
            VesselPosition.E08,
            VesselPosition.E09,
            VesselPosition.E10,
            VesselPosition.E11,
            VesselPosition.E12,
            VesselPosition.F01,
            VesselPosition.F02,
            VesselPosition.F03,
            VesselPosition.F04,
            VesselPosition.F05,
            VesselPosition.F06,
            VesselPosition.F07,
            VesselPosition.F08,
            VesselPosition.F09,
            VesselPosition.F10,
            VesselPosition.F11,
            VesselPosition.F12,
            VesselPosition.G01,
            VesselPosition.G02,
            VesselPosition.G03,
            VesselPosition.G04,
            VesselPosition.G05,
            VesselPosition.G06,
            VesselPosition.G07,
            VesselPosition.G08,
            VesselPosition.G09,
            VesselPosition.G10,
            VesselPosition.G11,
            VesselPosition.G12,
            VesselPosition.H01,
            VesselPosition.H02,
            VesselPosition.H03,
            VesselPosition.H04,
            VesselPosition.H05,
            VesselPosition.H06,
            VesselPosition.H07,
            VesselPosition.H08,
            VesselPosition.H09,
            VesselPosition.H10,
            VesselPosition.H11,
            VesselPosition.H12
    )),
    // An entire 8 well plate (e.g. 10X chip).
    ALL8("ALL8", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.B01,
            VesselPosition.C01,
            VesselPosition.D01,
            VesselPosition.E01,
            VesselPosition.F01,
            VesselPosition.G01,
            VesselPosition.H01)),
    // Columns 1-6 of a 96 well plate, ordered by row; source for transfer into Fluidigm chip
    P96COLS1_6BYROW("P96COLS1-6BYROW", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A02,
            VesselPosition.A03,
            VesselPosition.A04,
            VesselPosition.A05,
            VesselPosition.A06,
            VesselPosition.B01,
            VesselPosition.B02,
            VesselPosition.B03,
            VesselPosition.B04,
            VesselPosition.B05,
            VesselPosition.B06,
            VesselPosition.C01,
            VesselPosition.C02,
            VesselPosition.C03,
            VesselPosition.C04,
            VesselPosition.C05,
            VesselPosition.C06,
            VesselPosition.D01,
            VesselPosition.D02,
            VesselPosition.D03,
            VesselPosition.D04,
            VesselPosition.D05,
            VesselPosition.D06,
            VesselPosition.E01,
            VesselPosition.E02,
            VesselPosition.E03,
            VesselPosition.E04,
            VesselPosition.E05,
            VesselPosition.E06,
            VesselPosition.F01,
            VesselPosition.F02,
            VesselPosition.F03,
            VesselPosition.F04,
            VesselPosition.F05,
            VesselPosition.F06,
            VesselPosition.G01,
            VesselPosition.G02,
            VesselPosition.G03,
            VesselPosition.G04,
            VesselPosition.G05,
            VesselPosition.G06,
            VesselPosition.H01,
            VesselPosition.H02,
            VesselPosition.H03,
            VesselPosition.H04,
            VesselPosition.H05,
            VesselPosition.H06
    )),
    // 3 columns by 6 rows, starting at A1; source for transfer into 8x6 Eco plate
    P3_BY_6_A1("3BY6A1", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A02,
            VesselPosition.A03,
            VesselPosition.B01,
            VesselPosition.B02,
            VesselPosition.B03,
            VesselPosition.C01,
            VesselPosition.C02,
            VesselPosition.C03,
            VesselPosition.D01,
            VesselPosition.D02,
            VesselPosition.D03,
            VesselPosition.E01,
            VesselPosition.E02,
            VesselPosition.E03,
            VesselPosition.F01,
            VesselPosition.F02,
            VesselPosition.F03
            )),
    // In an 8 by 6 plate, start at A3 and skip rows, i.e. A3, C3, E3, A4 etc.
    P8_BY_6_A3_ALT_ROWS("8BY6A3ALTROWS", Arrays.asList(
            VesselPosition.A03,
            VesselPosition.A04,
            VesselPosition.A05,
            VesselPosition.A06,
            VesselPosition.A07,
            VesselPosition.A08,
            VesselPosition.C03,
            VesselPosition.C04,
            VesselPosition.C05,
            VesselPosition.C06,
            VesselPosition.C07,
            VesselPosition.C08,
            VesselPosition.E03,
            VesselPosition.E04,
            VesselPosition.E05,
            VesselPosition.E06,
            VesselPosition.E07,
            VesselPosition.E08
            )),
    // In an 8 by 6 plate, start at B3 and skip rows, i.e. B3, D3, F3, B4 etc.
    P8_BY_6_B3_ALT_ROWS("8BY6B3ALTROWS", Arrays.asList(
            VesselPosition.B03,
            VesselPosition.B04,
            VesselPosition.B05,
            VesselPosition.B06,
            VesselPosition.B07,
            VesselPosition.B08,
            VesselPosition.D03,
            VesselPosition.D04,
            VesselPosition.D05,
            VesselPosition.D06,
            VesselPosition.D07,
            VesselPosition.D08,
            VesselPosition.F03,
            VesselPosition.F04,
            VesselPosition.F05,
            VesselPosition.F06,
            VesselPosition.F07,
            VesselPosition.F08
    )),
    // 2 columns by 6 rows, starting at A1; source for transfer into 8x6 Eco plate
    P2_BY_6_A1("2BY6A1", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A02,
            VesselPosition.B01,
            VesselPosition.B02,
            VesselPosition.C01,
            VesselPosition.C02,
            VesselPosition.D01,
            VesselPosition.D02,
            VesselPosition.E01,
            VesselPosition.E02,
            VesselPosition.F01,
            VesselPosition.F02
    )),
    // In an 8 by 6 plate, start at A3 and go down column wise for 2 cols
    P8_BY_6_A3_COL_WISE_2("8BY6A3COLWISE2", Arrays.asList(
            VesselPosition.A03,
            VesselPosition.B03,
            VesselPosition.C03,
            VesselPosition.D03,
            VesselPosition.E03,
            VesselPosition.F03,
            VesselPosition.A04,
            VesselPosition.B04,
            VesselPosition.C04,
            VesselPosition.D04,
            VesselPosition.E04,
            VesselPosition.F04
    )),
    // In an 8 by 6 plate, start at Col 5 but with a flipped pattern for each pair going down.
    P8_BY_6_A5_COL_WISE_2_ALT("8BY6A5COLWISE2_ALT", Arrays.asList(
            VesselPosition.B05,
            VesselPosition.A05,
            VesselPosition.D05,
            VesselPosition.C05,
            VesselPosition.F05,
            VesselPosition.E05,
            VesselPosition.B06,
            VesselPosition.A06,
            VesselPosition.D06,
            VesselPosition.C06,
            VesselPosition.F06,
            VesselPosition.E06
    )),
    // In an 8 by 6 plate, start at A7 and go down column wise for 2 cols
    P8_BY_6_A7_COL_WISE_2("8BY6A7COLWISE2", Arrays.asList(
            VesselPosition.A07,
            VesselPosition.B07,
            VesselPosition.C07,
            VesselPosition.D07,
            VesselPosition.E07,
            VesselPosition.F07,
            VesselPosition.A08,
            VesselPosition.B08,
            VesselPosition.C08,
            VesselPosition.D08,
            VesselPosition.E08,
            VesselPosition.F08
    )),
    // Columns 4-6 of a 384 well plate, ordered by row; sample inputs for a Fluidigm 48.48 chip
    P384COLS4_6BYROW("P384COLS4-6BYROW", Arrays.asList(
            VesselPosition.A04,
            VesselPosition.A05,
            VesselPosition.A06,
            VesselPosition.B04,
            VesselPosition.B05,
            VesselPosition.B06,
            VesselPosition.C04,
            VesselPosition.C05,
            VesselPosition.C06,
            VesselPosition.D04,
            VesselPosition.D05,
            VesselPosition.D06,
            VesselPosition.E04,
            VesselPosition.E05,
            VesselPosition.E06,
            VesselPosition.F04,
            VesselPosition.F05,
            VesselPosition.F06,
            VesselPosition.G04,
            VesselPosition.G05,
            VesselPosition.G06,
            VesselPosition.H04,
            VesselPosition.H05,
            VesselPosition.H06,
            VesselPosition.I04,
            VesselPosition.I05,
            VesselPosition.I06,
            VesselPosition.J04,
            VesselPosition.J05,
            VesselPosition.J06,
            VesselPosition.K04,
            VesselPosition.K05,
            VesselPosition.K06,
            VesselPosition.L04,
            VesselPosition.L05,
            VesselPosition.L06,
            VesselPosition.M04,
            VesselPosition.M05,
            VesselPosition.M06,
            VesselPosition.N04,
            VesselPosition.N05,
            VesselPosition.N06,
            VesselPosition.O04,
            VesselPosition.O05,
            VesselPosition.O06,
            VesselPosition.P04,
            VesselPosition.P05,
            VesselPosition.P06
    )),
    // Sage DNA sizing cassette
    COL1ODDROWS("COL1ODDROWS", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.C01,
            VesselPosition.E01,
            VesselPosition.G01
    )),
    // Source for transfer into Sage
    FIRST4("FIRST4", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.B01,
            VesselPosition.C01,
            VesselPosition.D01
    )),
    // 12 tips, at intervals of 3 wells, starting at A1, i.e. A1, A4, A7, A10, D1 etc.
    S12TIP3INTERVALA1("12TIP3INTERVALA1", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A04,
            VesselPosition.A07,
            VesselPosition.A10,
            VesselPosition.D01,
            VesselPosition.D04,
            VesselPosition.D07,
            VesselPosition.D10,
            VesselPosition.G01,
            VesselPosition.G04,
            VesselPosition.G07,
            VesselPosition.G10
    )),
    // 12 tips, at intervals of 3 wells, starting at A2, i.e. A2, A5, A8, A11, D2 etc.
    S12TIP3INTERVALA2("12TIP3INTERVALA2", Arrays.asList(
            VesselPosition.A02,
            VesselPosition.A05,
            VesselPosition.A08,
            VesselPosition.A11,
            VesselPosition.D02,
            VesselPosition.D05,
            VesselPosition.D08,
            VesselPosition.D11,
            VesselPosition.G02,
            VesselPosition.G05,
            VesselPosition.G08,
            VesselPosition.G11
    )),
    // 12 tips, at intervals of 3 wells, starting at B1, i.e. B1, B4, B7, B10, E1 etc.
    S12TIP3INTERVALB1("12TIP3INTERVALB1", Arrays.asList(
            VesselPosition.B01,
            VesselPosition.B04,
            VesselPosition.B07,
            VesselPosition.B10,
            VesselPosition.E01,
            VesselPosition.E04,
            VesselPosition.E07,
            VesselPosition.E10,
            VesselPosition.H01,
            VesselPosition.H04,
            VesselPosition.H07,
            VesselPosition.H10
    )),
    // 12 tips, at intervals of 3 wells, starting at B2, i.e. B2, B5, B8, B11, E2 etc.
    S12TIP3INTERVALB2("12TIP3INTERVALB2", Arrays.asList(
            VesselPosition.B02,
            VesselPosition.B05,
            VesselPosition.B08,
            VesselPosition.B11,
            VesselPosition.E02,
            VesselPosition.E05,
            VesselPosition.E08,
            VesselPosition.E11,
            VesselPosition.H02,
            VesselPosition.H05,
            VesselPosition.H08,
            VesselPosition.H11
    )),
    // 24 tips, at intervals of 2 wells, starting at A1, i.e. A1, A3, A5, A7, A9, A11, C1 etc.
    S24TIP2INTERVALA1("24TIP2INTERVALA1", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A03,
            VesselPosition.A05,
            VesselPosition.A07,
            VesselPosition.A09,
            VesselPosition.A11,
            VesselPosition.C01,
            VesselPosition.C03,
            VesselPosition.C05,
            VesselPosition.C07,
            VesselPosition.C09,
            VesselPosition.C11,
            VesselPosition.E01,
            VesselPosition.E03,
            VesselPosition.E05,
            VesselPosition.E07,
            VesselPosition.E09,
            VesselPosition.E11,
            VesselPosition.G01,
            VesselPosition.G03,
            VesselPosition.G05,
            VesselPosition.G07,
            VesselPosition.G09,
            VesselPosition.G11
    )),
    // 24 tips, at intervals of 2 wells, starting at A2, i.e. A2, A4, A6, A8, A10, A12, C2 etc.
    S24TIP2INTERVALA2("24TIP2INTERVALA2", Arrays.asList(
            VesselPosition.A02,
            VesselPosition.A04,
            VesselPosition.A06,
            VesselPosition.A08,
            VesselPosition.A10,
            VesselPosition.A12,
            VesselPosition.C02,
            VesselPosition.C04,
            VesselPosition.C06,
            VesselPosition.C08,
            VesselPosition.C10,
            VesselPosition.C12,
            VesselPosition.E02,
            VesselPosition.E04,
            VesselPosition.E06,
            VesselPosition.E08,
            VesselPosition.E10,
            VesselPosition.E12,
            VesselPosition.G02,
            VesselPosition.G04,
            VesselPosition.G06,
            VesselPosition.G08,
            VesselPosition.G10,
            VesselPosition.G12
    )),
    // 24 tips, at intervals of 2 wells, starting at B1, i.e. B1, B3, B5, B7, B9, B11, D1 etc.
    S24TIP2INTERVALB1("24TIP2INTERVALB1", Arrays.asList(
            VesselPosition.B01,
            VesselPosition.B03,
            VesselPosition.B05,
            VesselPosition.B07,
            VesselPosition.B09,
            VesselPosition.B11,
            VesselPosition.D01,
            VesselPosition.D03,
            VesselPosition.D05,
            VesselPosition.D07,
            VesselPosition.D09,
            VesselPosition.D11,
            VesselPosition.F01,
            VesselPosition.F03,
            VesselPosition.F05,
            VesselPosition.F07,
            VesselPosition.F09,
            VesselPosition.F11,
            VesselPosition.H01,
            VesselPosition.H03,
            VesselPosition.H05,
            VesselPosition.H07,
            VesselPosition.H09,
            VesselPosition.H11
    )),
    // 24 tips, at intervals of 2 wells, starting at B2, i.e. B2, B4, B6, B8, B10, B12, D2 etc.
    S24TIP2INTERVALB2("24TIP2INTERVALB2", Arrays.asList(
            VesselPosition.B02,
            VesselPosition.B04,
            VesselPosition.B06,
            VesselPosition.B08,
            VesselPosition.B10,
            VesselPosition.B12,
            VesselPosition.D02,
            VesselPosition.D04,
            VesselPosition.D06,
            VesselPosition.D08,
            VesselPosition.D10,
            VesselPosition.D12,
            VesselPosition.F02,
            VesselPosition.F04,
            VesselPosition.F06,
            VesselPosition.F08,
            VesselPosition.F10,
            VesselPosition.F12,
            VesselPosition.H02,
            VesselPosition.H04,
            VesselPosition.H06,
            VesselPosition.H08,
            VesselPosition.H10,
            VesselPosition.H12
    )),
    STRIP_TUBE8("STRIP_TUBE8", Arrays.asList(
            VesselPosition.TUBE1,
            VesselPosition.TUBE2,
            VesselPosition.TUBE3,
            VesselPosition.TUBE4,
            VesselPosition.TUBE5,
            VesselPosition.TUBE6,
            VesselPosition.TUBE7,
            VesselPosition.TUBE8
    )),
    STRIP_TUBE2("STRIP_TUBE2", Arrays.asList(
            VesselPosition.TUBE1,
            VesselPosition.TUBE2
    )),
    FLOWCELL8("FLOWCELL8", Arrays.asList(
            VesselPosition.LANE1,
            VesselPosition.LANE2,
            VesselPosition.LANE3,
            VesselPosition.LANE4,
            VesselPosition.LANE5,
            VesselPosition.LANE6,
            VesselPosition.LANE7,
            VesselPosition.LANE8
    )),
    // todo jmt should be FLOWCELL2?
    ALL2("ALL2", Arrays.asList(
            VesselPosition.LANE1,
            VesselPosition.LANE2
    )),
    LANE1("LANE1", Arrays.asList(
            VesselPosition.LANE1
    )),
    LANE2("LANE2", Arrays.asList(
            VesselPosition.LANE2
    )),
    // Quadrant containing the odd rows and odd columns on a 384-well plate.
    P384_96TIP_1INTERVAL_A1("P384_96TIP_1INTERVAL_A1", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A03,
            VesselPosition.A05,
            VesselPosition.A07,
            VesselPosition.A09,
            VesselPosition.A11,
            VesselPosition.A13,
            VesselPosition.A15,
            VesselPosition.A17,
            VesselPosition.A19,
            VesselPosition.A21,
            VesselPosition.A23,
            VesselPosition.C01,
            VesselPosition.C03,
            VesselPosition.C05,
            VesselPosition.C07,
            VesselPosition.C09,
            VesselPosition.C11,
            VesselPosition.C13,
            VesselPosition.C15,
            VesselPosition.C17,
            VesselPosition.C19,
            VesselPosition.C21,
            VesselPosition.C23,
            VesselPosition.E01,
            VesselPosition.E03,
            VesselPosition.E05,
            VesselPosition.E07,
            VesselPosition.E09,
            VesselPosition.E11,
            VesselPosition.E13,
            VesselPosition.E15,
            VesselPosition.E17,
            VesselPosition.E19,
            VesselPosition.E21,
            VesselPosition.E23,
            VesselPosition.G01,
            VesselPosition.G03,
            VesselPosition.G05,
            VesselPosition.G07,
            VesselPosition.G09,
            VesselPosition.G11,
            VesselPosition.G13,
            VesselPosition.G15,
            VesselPosition.G17,
            VesselPosition.G19,
            VesselPosition.G21,
            VesselPosition.G23,
            VesselPosition.I01,
            VesselPosition.I03,
            VesselPosition.I05,
            VesselPosition.I07,
            VesselPosition.I09,
            VesselPosition.I11,
            VesselPosition.I13,
            VesselPosition.I15,
            VesselPosition.I17,
            VesselPosition.I19,
            VesselPosition.I21,
            VesselPosition.I23,
            VesselPosition.K01,
            VesselPosition.K03,
            VesselPosition.K05,
            VesselPosition.K07,
            VesselPosition.K09,
            VesselPosition.K11,
            VesselPosition.K13,
            VesselPosition.K15,
            VesselPosition.K17,
            VesselPosition.K19,
            VesselPosition.K21,
            VesselPosition.K23,
            VesselPosition.M01,
            VesselPosition.M03,
            VesselPosition.M05,
            VesselPosition.M07,
            VesselPosition.M09,
            VesselPosition.M11,
            VesselPosition.M13,
            VesselPosition.M15,
            VesselPosition.M17,
            VesselPosition.M19,
            VesselPosition.M21,
            VesselPosition.M23,
            VesselPosition.O01,
            VesselPosition.O03,
            VesselPosition.O05,
            VesselPosition.O07,
            VesselPosition.O09,
            VesselPosition.O11,
            VesselPosition.O13,
            VesselPosition.O15,
            VesselPosition.O17,
            VesselPosition.O19,
            VesselPosition.O21,
            VesselPosition.O23)),
    // Quadrant containing the odd rows and even columns on a 384-well plate.
    P384_96TIP_1INTERVAL_A2("P384_96TIP_1INTERVAL_A2", Arrays.asList(
            VesselPosition.A02,
            VesselPosition.A04,
            VesselPosition.A06,
            VesselPosition.A08,
            VesselPosition.A10,
            VesselPosition.A12,
            VesselPosition.A14,
            VesselPosition.A16,
            VesselPosition.A18,
            VesselPosition.A20,
            VesselPosition.A22,
            VesselPosition.A24,
            VesselPosition.C02,
            VesselPosition.C04,
            VesselPosition.C06,
            VesselPosition.C08,
            VesselPosition.C10,
            VesselPosition.C12,
            VesselPosition.C14,
            VesselPosition.C16,
            VesselPosition.C18,
            VesselPosition.C20,
            VesselPosition.C22,
            VesselPosition.C24,
            VesselPosition.E02,
            VesselPosition.E04,
            VesselPosition.E06,
            VesselPosition.E08,
            VesselPosition.E10,
            VesselPosition.E12,
            VesselPosition.E14,
            VesselPosition.E16,
            VesselPosition.E18,
            VesselPosition.E20,
            VesselPosition.E22,
            VesselPosition.E24,
            VesselPosition.G02,
            VesselPosition.G04,
            VesselPosition.G06,
            VesselPosition.G08,
            VesselPosition.G10,
            VesselPosition.G12,
            VesselPosition.G14,
            VesselPosition.G16,
            VesselPosition.G18,
            VesselPosition.G20,
            VesselPosition.G22,
            VesselPosition.G24,
            VesselPosition.I02,
            VesselPosition.I04,
            VesselPosition.I06,
            VesselPosition.I08,
            VesselPosition.I10,
            VesselPosition.I12,
            VesselPosition.I14,
            VesselPosition.I16,
            VesselPosition.I18,
            VesselPosition.I20,
            VesselPosition.I22,
            VesselPosition.I24,
            VesselPosition.K02,
            VesselPosition.K04,
            VesselPosition.K06,
            VesselPosition.K08,
            VesselPosition.K10,
            VesselPosition.K12,
            VesselPosition.K14,
            VesselPosition.K16,
            VesselPosition.K18,
            VesselPosition.K20,
            VesselPosition.K22,
            VesselPosition.K24,
            VesselPosition.M02,
            VesselPosition.M04,
            VesselPosition.M06,
            VesselPosition.M08,
            VesselPosition.M10,
            VesselPosition.M12,
            VesselPosition.M14,
            VesselPosition.M16,
            VesselPosition.M18,
            VesselPosition.M20,
            VesselPosition.M22,
            VesselPosition.M24,
            VesselPosition.O02,
            VesselPosition.O04,
            VesselPosition.O06,
            VesselPosition.O08,
            VesselPosition.O10,
            VesselPosition.O12,
            VesselPosition.O14,
            VesselPosition.O16,
            VesselPosition.O18,
            VesselPosition.O20,
            VesselPosition.O22,
            VesselPosition.O24)),
    // Quadrant containing the even rows and odd columns on a 384-well plate.
    P384_96TIP_1INTERVAL_B1("P384_96TIP_1INTERVAL_B1", Arrays.asList(
            VesselPosition.B01,
            VesselPosition.B03,
            VesselPosition.B05,
            VesselPosition.B07,
            VesselPosition.B09,
            VesselPosition.B11,
            VesselPosition.B13,
            VesselPosition.B15,
            VesselPosition.B17,
            VesselPosition.B19,
            VesselPosition.B21,
            VesselPosition.B23,
            VesselPosition.D01,
            VesselPosition.D03,
            VesselPosition.D05,
            VesselPosition.D07,
            VesselPosition.D09,
            VesselPosition.D11,
            VesselPosition.D13,
            VesselPosition.D15,
            VesselPosition.D17,
            VesselPosition.D19,
            VesselPosition.D21,
            VesselPosition.D23,
            VesselPosition.F01,
            VesselPosition.F03,
            VesselPosition.F05,
            VesselPosition.F07,
            VesselPosition.F09,
            VesselPosition.F11,
            VesselPosition.F13,
            VesselPosition.F15,
            VesselPosition.F17,
            VesselPosition.F19,
            VesselPosition.F21,
            VesselPosition.F23,
            VesselPosition.H01,
            VesselPosition.H03,
            VesselPosition.H05,
            VesselPosition.H07,
            VesselPosition.H09,
            VesselPosition.H11,
            VesselPosition.H13,
            VesselPosition.H15,
            VesselPosition.H17,
            VesselPosition.H19,
            VesselPosition.H21,
            VesselPosition.H23,
            VesselPosition.J01,
            VesselPosition.J03,
            VesselPosition.J05,
            VesselPosition.J07,
            VesselPosition.J09,
            VesselPosition.J11,
            VesselPosition.J13,
            VesselPosition.J15,
            VesselPosition.J17,
            VesselPosition.J19,
            VesselPosition.J21,
            VesselPosition.J23,
            VesselPosition.L01,
            VesselPosition.L03,
            VesselPosition.L05,
            VesselPosition.L07,
            VesselPosition.L09,
            VesselPosition.L11,
            VesselPosition.L13,
            VesselPosition.L15,
            VesselPosition.L17,
            VesselPosition.L19,
            VesselPosition.L21,
            VesselPosition.L23,
            VesselPosition.N01,
            VesselPosition.N03,
            VesselPosition.N05,
            VesselPosition.N07,
            VesselPosition.N09,
            VesselPosition.N11,
            VesselPosition.N13,
            VesselPosition.N15,
            VesselPosition.N17,
            VesselPosition.N19,
            VesselPosition.N21,
            VesselPosition.N23,
            VesselPosition.P01,
            VesselPosition.P03,
            VesselPosition.P05,
            VesselPosition.P07,
            VesselPosition.P09,
            VesselPosition.P11,
            VesselPosition.P13,
            VesselPosition.P15,
            VesselPosition.P17,
            VesselPosition.P19,
            VesselPosition.P21,
            VesselPosition.P23)),
    // Quadrant containing the even rows and even columns on a 384-well plate.
    P384_96TIP_1INTERVAL_B2("P384_96TIP_1INTERVAL_B2", Arrays.asList(
            VesselPosition.B02,
            VesselPosition.B04,
            VesselPosition.B06,
            VesselPosition.B08,
            VesselPosition.B10,
            VesselPosition.B12,
            VesselPosition.B14,
            VesselPosition.B16,
            VesselPosition.B18,
            VesselPosition.B20,
            VesselPosition.B22,
            VesselPosition.B24,
            VesselPosition.D02,
            VesselPosition.D04,
            VesselPosition.D06,
            VesselPosition.D08,
            VesselPosition.D10,
            VesselPosition.D12,
            VesselPosition.D14,
            VesselPosition.D16,
            VesselPosition.D18,
            VesselPosition.D20,
            VesselPosition.D22,
            VesselPosition.D24,
            VesselPosition.F02,
            VesselPosition.F04,
            VesselPosition.F06,
            VesselPosition.F08,
            VesselPosition.F10,
            VesselPosition.F12,
            VesselPosition.F14,
            VesselPosition.F16,
            VesselPosition.F18,
            VesselPosition.F20,
            VesselPosition.F22,
            VesselPosition.F24,
            VesselPosition.H02,
            VesselPosition.H04,
            VesselPosition.H06,
            VesselPosition.H08,
            VesselPosition.H10,
            VesselPosition.H12,
            VesselPosition.H14,
            VesselPosition.H16,
            VesselPosition.H18,
            VesselPosition.H20,
            VesselPosition.H22,
            VesselPosition.H24,
            VesselPosition.J02,
            VesselPosition.J04,
            VesselPosition.J06,
            VesselPosition.J08,
            VesselPosition.J10,
            VesselPosition.J12,
            VesselPosition.J14,
            VesselPosition.J16,
            VesselPosition.J18,
            VesselPosition.J20,
            VesselPosition.J22,
            VesselPosition.J24,
            VesselPosition.L02,
            VesselPosition.L04,
            VesselPosition.L06,
            VesselPosition.L08,
            VesselPosition.L10,
            VesselPosition.L12,
            VesselPosition.L14,
            VesselPosition.L16,
            VesselPosition.L18,
            VesselPosition.L20,
            VesselPosition.L22,
            VesselPosition.L24,
            VesselPosition.N02,
            VesselPosition.N04,
            VesselPosition.N06,
            VesselPosition.N08,
            VesselPosition.N10,
            VesselPosition.N12,
            VesselPosition.N14,
            VesselPosition.N16,
            VesselPosition.N18,
            VesselPosition.N20,
            VesselPosition.N22,
            VesselPosition.N24,
            VesselPosition.P02,
            VesselPosition.P04,
            VesselPosition.P06,
            VesselPosition.P08,
            VesselPosition.P10,
            VesselPosition.P12,
            VesselPosition.P14,
            VesselPosition.P16,
            VesselPosition.P18,
            VesselPosition.P20,
            VesselPosition.P22,
            VesselPosition.P24)),
    // The first column of a 96 well plate
    P96_COL1("P96_COL1", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.B01,
            VesselPosition.C01,
            VesselPosition.D01,
            VesselPosition.E01,
            VesselPosition.F01,
            VesselPosition.G01,
            VesselPosition.H01)),
    P96_COL2("P96_COL2", Arrays.asList(
            VesselPosition.A02,
            VesselPosition.B02,
            VesselPosition.C02,
            VesselPosition.D02,
            VesselPosition.E02,
            VesselPosition.F02,
            VesselPosition.G02,
            VesselPosition.H02)),
    P96_COL3("P96_COL3", Arrays.asList(
            VesselPosition.A03,
            VesselPosition.B03,
            VesselPosition.C03,
            VesselPosition.D03,
            VesselPosition.E03,
            VesselPosition.F03,
            VesselPosition.G03,
            VesselPosition.H03)),
    P96_COL4("P96_COL4", Arrays.asList(
            VesselPosition.A04,
            VesselPosition.B04,
            VesselPosition.C04,
            VesselPosition.D04,
            VesselPosition.E04,
            VesselPosition.F04,
            VesselPosition.G04,
            VesselPosition.H04)),
    P96_COL5("P96_COL5", Arrays.asList(
            VesselPosition.A05,
            VesselPosition.B05,
            VesselPosition.C05,
            VesselPosition.D05,
            VesselPosition.E05,
            VesselPosition.F05,
            VesselPosition.G05,
            VesselPosition.H05)),
    P96_COL6("P96_COL6", Arrays.asList(
            VesselPosition.A06,
            VesselPosition.B06,
            VesselPosition.C06,
            VesselPosition.D06,
            VesselPosition.E06,
            VesselPosition.F06,
            VesselPosition.G06,
            VesselPosition.H06)),
    P96_COL7("P96_COL7", Arrays.asList(
            VesselPosition.A07,
            VesselPosition.B07,
            VesselPosition.C07,
            VesselPosition.D07,
            VesselPosition.E07,
            VesselPosition.F07,
            VesselPosition.G07,
            VesselPosition.H07)),
    P96_COL8("P96_COL8", Arrays.asList(
            VesselPosition.A08,
            VesselPosition.B08,
            VesselPosition.C08,
            VesselPosition.D08,
            VesselPosition.E08,
            VesselPosition.F08,
            VesselPosition.G08,
            VesselPosition.H08)),
    P96_COL9("P96_COL9", Arrays.asList(
            VesselPosition.A09,
            VesselPosition.B09,
            VesselPosition.C09,
            VesselPosition.D09,
            VesselPosition.E09,
            VesselPosition.F09,
            VesselPosition.G09,
            VesselPosition.H09)),
    P96_COL10("P96_COL10", Arrays.asList(
            VesselPosition.A10,
            VesselPosition.B10,
            VesselPosition.C10,
            VesselPosition.D10,
            VesselPosition.E10,
            VesselPosition.F10,
            VesselPosition.G10,
            VesselPosition.H10)),
    P96_COL11("P96_COL11", Arrays.asList(
            VesselPosition.A11,
            VesselPosition.B11,
            VesselPosition.C11,
            VesselPosition.D11,
            VesselPosition.E11,
            VesselPosition.F11,
            VesselPosition.G11,
            VesselPosition.H11)),
    P96_COL12("P96_COL12", Arrays.asList(
            VesselPosition.A12,
            VesselPosition.B12,
            VesselPosition.C12,
            VesselPosition.D12,
            VesselPosition.E12,
            VesselPosition.F12,
            VesselPosition.G12,
            VesselPosition.H12)),
    // The first two rows of a 96 well plate
    P96_ROWSAB("P96_ROWSAB", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A02,
            VesselPosition.A03,
            VesselPosition.A04,
            VesselPosition.A05,
            VesselPosition.A06,
            VesselPosition.A07,
            VesselPosition.A08,
            VesselPosition.A09,
            VesselPosition.A10,
            VesselPosition.A11,
            VesselPosition.A12,
            VesselPosition.B01,
            VesselPosition.B02,
            VesselPosition.B03,
            VesselPosition.B04,
            VesselPosition.B05,
            VesselPosition.B06,
            VesselPosition.B07,
            VesselPosition.B08,
            VesselPosition.B09,
            VesselPosition.B10,
            VesselPosition.B11,
            VesselPosition.B12)),
    // The first eight columns in the first row of a 96 well plate (result of extraction)
    P96_ROWA_8("P96_ROWA_8", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A02,
            VesselPosition.A03,
            VesselPosition.A04,
            VesselPosition.A05,
            VesselPosition.A06,
            VesselPosition.A07,
            VesselPosition.A08)),
    // In a 384 well plate, alternate wells in column 2, starting at row B
    P384_COL2_1INTERVAL_B("P384_COL2_1INTERVAL_B", Arrays.asList(
            VesselPosition.B02,
            VesselPosition.D02,
            VesselPosition.F02,
            VesselPosition.H02,
            VesselPosition.J02,
            VesselPosition.L02,
            VesselPosition.N02,
            VesselPosition.P02)),
    // In a 384 well plate, alternate wells in column 4, starting at row B
    P384_COL4_1INTERVAL_B("P384_COL4_1INTERVAL_B", Arrays.asList(
            VesselPosition.B04,
            VesselPosition.D04,
            VesselPosition.F04,
            VesselPosition.H04,
            VesselPosition.J04,
            VesselPosition.L04,
            VesselPosition.N04,
            VesselPosition.P04)),
    // In a 384 well plate, alternate wells in column 6, starting at row B
    P384_COL6_1INTERVAL_B("P384_COL6_1INTERVAL_B", Arrays.asList(
            VesselPosition.B06,
            VesselPosition.D06,
            VesselPosition.F06,
            VesselPosition.H06,
            VesselPosition.J06,
            VesselPosition.L06,
            VesselPosition.N06,
            VesselPosition.P06)),
    // In a 384 well plate, alternate wells in column 8, starting at row B
    P384_COL8_1INTERVAL_B("P384_COL8_1INTERVAL_B", Arrays.asList(
            VesselPosition.B08,
            VesselPosition.D08,
            VesselPosition.F08,
            VesselPosition.H08,
            VesselPosition.J08,
            VesselPosition.L08,
            VesselPosition.N08,
            VesselPosition.P08)),
    // In a 384 well plate, alternate wells in column 10, starting at row B
    P384_COL10_1INTERVAL_B("P384_COL10_1INTERVAL_B", Arrays.asList(
            VesselPosition.B10,
            VesselPosition.D10,
            VesselPosition.F10,
            VesselPosition.H10,
            VesselPosition.J10,
            VesselPosition.L10,
            VesselPosition.N10,
            VesselPosition.P10)),
    // In a 384 well plate, alternate wells in column 12, starting at row B
    P384_COL12_1INTERVAL_B("P384_COL12_1INTERVAL_B", Arrays.asList(
            VesselPosition.B12,
            VesselPosition.D12,
            VesselPosition.F12,
            VesselPosition.H12,
            VesselPosition.J12,
            VesselPosition.L12,
            VesselPosition.N12,
            VesselPosition.P12)),
    // All wells in a 384 well plate
    ALL384("ALL384", Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A02,
            VesselPosition.A03,
            VesselPosition.A04,
            VesselPosition.A05,
            VesselPosition.A06,
            VesselPosition.A07,
            VesselPosition.A08,
            VesselPosition.A09,
            VesselPosition.A10,
            VesselPosition.A11,
            VesselPosition.A12,
            VesselPosition.A13,
            VesselPosition.A14,
            VesselPosition.A15,
            VesselPosition.A16,
            VesselPosition.A17,
            VesselPosition.A18,
            VesselPosition.A19,
            VesselPosition.A20,
            VesselPosition.A21,
            VesselPosition.A22,
            VesselPosition.A23,
            VesselPosition.A24,
            VesselPosition.B01,
            VesselPosition.B02,
            VesselPosition.B03,
            VesselPosition.B04,
            VesselPosition.B05,
            VesselPosition.B06,
            VesselPosition.B07,
            VesselPosition.B08,
            VesselPosition.B09,
            VesselPosition.B10,
            VesselPosition.B11,
            VesselPosition.B12,
            VesselPosition.B13,
            VesselPosition.B14,
            VesselPosition.B15,
            VesselPosition.B16,
            VesselPosition.B17,
            VesselPosition.B18,
            VesselPosition.B19,
            VesselPosition.B20,
            VesselPosition.B21,
            VesselPosition.B22,
            VesselPosition.B23,
            VesselPosition.B24,
            VesselPosition.C01,
            VesselPosition.C02,
            VesselPosition.C03,
            VesselPosition.C04,
            VesselPosition.C05,
            VesselPosition.C06,
            VesselPosition.C07,
            VesselPosition.C08,
            VesselPosition.C09,
            VesselPosition.C10,
            VesselPosition.C11,
            VesselPosition.C12,
            VesselPosition.C13,
            VesselPosition.C14,
            VesselPosition.C15,
            VesselPosition.C16,
            VesselPosition.C17,
            VesselPosition.C18,
            VesselPosition.C19,
            VesselPosition.C20,
            VesselPosition.C21,
            VesselPosition.C22,
            VesselPosition.C23,
            VesselPosition.C24,
            VesselPosition.D01,
            VesselPosition.D02,
            VesselPosition.D03,
            VesselPosition.D04,
            VesselPosition.D05,
            VesselPosition.D06,
            VesselPosition.D07,
            VesselPosition.D08,
            VesselPosition.D09,
            VesselPosition.D10,
            VesselPosition.D11,
            VesselPosition.D12,
            VesselPosition.D13,
            VesselPosition.D14,
            VesselPosition.D15,
            VesselPosition.D16,
            VesselPosition.D17,
            VesselPosition.D18,
            VesselPosition.D19,
            VesselPosition.D20,
            VesselPosition.D21,
            VesselPosition.D22,
            VesselPosition.D23,
            VesselPosition.D24,
            VesselPosition.E01,
            VesselPosition.E02,
            VesselPosition.E03,
            VesselPosition.E04,
            VesselPosition.E05,
            VesselPosition.E06,
            VesselPosition.E07,
            VesselPosition.E08,
            VesselPosition.E09,
            VesselPosition.E10,
            VesselPosition.E11,
            VesselPosition.E12,
            VesselPosition.E13,
            VesselPosition.E14,
            VesselPosition.E15,
            VesselPosition.E16,
            VesselPosition.E17,
            VesselPosition.E18,
            VesselPosition.E19,
            VesselPosition.E20,
            VesselPosition.E21,
            VesselPosition.E22,
            VesselPosition.E23,
            VesselPosition.E24,
            VesselPosition.F01,
            VesselPosition.F02,
            VesselPosition.F03,
            VesselPosition.F04,
            VesselPosition.F05,
            VesselPosition.F06,
            VesselPosition.F07,
            VesselPosition.F08,
            VesselPosition.F09,
            VesselPosition.F10,
            VesselPosition.F11,
            VesselPosition.F12,
            VesselPosition.F13,
            VesselPosition.F14,
            VesselPosition.F15,
            VesselPosition.F16,
            VesselPosition.F17,
            VesselPosition.F18,
            VesselPosition.F19,
            VesselPosition.F20,
            VesselPosition.F21,
            VesselPosition.F22,
            VesselPosition.F23,
            VesselPosition.F24,
            VesselPosition.G01,
            VesselPosition.G02,
            VesselPosition.G03,
            VesselPosition.G04,
            VesselPosition.G05,
            VesselPosition.G06,
            VesselPosition.G07,
            VesselPosition.G08,
            VesselPosition.G09,
            VesselPosition.G10,
            VesselPosition.G11,
            VesselPosition.G12,
            VesselPosition.G13,
            VesselPosition.G14,
            VesselPosition.G15,
            VesselPosition.G16,
            VesselPosition.G17,
            VesselPosition.G18,
            VesselPosition.G19,
            VesselPosition.G20,
            VesselPosition.G21,
            VesselPosition.G22,
            VesselPosition.G23,
            VesselPosition.G24,
            VesselPosition.H01,
            VesselPosition.H02,
            VesselPosition.H03,
            VesselPosition.H04,
            VesselPosition.H05,
            VesselPosition.H06,
            VesselPosition.H07,
            VesselPosition.H08,
            VesselPosition.H09,
            VesselPosition.H10,
            VesselPosition.H11,
            VesselPosition.H12,
            VesselPosition.H13,
            VesselPosition.H14,
            VesselPosition.H15,
            VesselPosition.H16,
            VesselPosition.H17,
            VesselPosition.H18,
            VesselPosition.H19,
            VesselPosition.H20,
            VesselPosition.H21,
            VesselPosition.H22,
            VesselPosition.H23,
            VesselPosition.H24,
            VesselPosition.I01,
            VesselPosition.I02,
            VesselPosition.I03,
            VesselPosition.I04,
            VesselPosition.I05,
            VesselPosition.I06,
            VesselPosition.I07,
            VesselPosition.I08,
            VesselPosition.I09,
            VesselPosition.I10,
            VesselPosition.I11,
            VesselPosition.I12,
            VesselPosition.I13,
            VesselPosition.I14,
            VesselPosition.I15,
            VesselPosition.I16,
            VesselPosition.I17,
            VesselPosition.I18,
            VesselPosition.I19,
            VesselPosition.I20,
            VesselPosition.I21,
            VesselPosition.I22,
            VesselPosition.I23,
            VesselPosition.I24,
            VesselPosition.J01,
            VesselPosition.J02,
            VesselPosition.J03,
            VesselPosition.J04,
            VesselPosition.J05,
            VesselPosition.J06,
            VesselPosition.J07,
            VesselPosition.J08,
            VesselPosition.J09,
            VesselPosition.J10,
            VesselPosition.J11,
            VesselPosition.J12,
            VesselPosition.J13,
            VesselPosition.J14,
            VesselPosition.J15,
            VesselPosition.J16,
            VesselPosition.J17,
            VesselPosition.J18,
            VesselPosition.J19,
            VesselPosition.J20,
            VesselPosition.J21,
            VesselPosition.J22,
            VesselPosition.J23,
            VesselPosition.J24,
            VesselPosition.K01,
            VesselPosition.K02,
            VesselPosition.K03,
            VesselPosition.K04,
            VesselPosition.K05,
            VesselPosition.K06,
            VesselPosition.K07,
            VesselPosition.K08,
            VesselPosition.K09,
            VesselPosition.K10,
            VesselPosition.K11,
            VesselPosition.K12,
            VesselPosition.K13,
            VesselPosition.K14,
            VesselPosition.K15,
            VesselPosition.K16,
            VesselPosition.K17,
            VesselPosition.K18,
            VesselPosition.K19,
            VesselPosition.K20,
            VesselPosition.K21,
            VesselPosition.K22,
            VesselPosition.K23,
            VesselPosition.K24,
            VesselPosition.L01,
            VesselPosition.L02,
            VesselPosition.L03,
            VesselPosition.L04,
            VesselPosition.L05,
            VesselPosition.L06,
            VesselPosition.L07,
            VesselPosition.L08,
            VesselPosition.L09,
            VesselPosition.L10,
            VesselPosition.L11,
            VesselPosition.L12,
            VesselPosition.L13,
            VesselPosition.L14,
            VesselPosition.L15,
            VesselPosition.L16,
            VesselPosition.L17,
            VesselPosition.L18,
            VesselPosition.L19,
            VesselPosition.L20,
            VesselPosition.L21,
            VesselPosition.L22,
            VesselPosition.L23,
            VesselPosition.L24,
            VesselPosition.M01,
            VesselPosition.M02,
            VesselPosition.M03,
            VesselPosition.M04,
            VesselPosition.M05,
            VesselPosition.M06,
            VesselPosition.M07,
            VesselPosition.M08,
            VesselPosition.M09,
            VesselPosition.M10,
            VesselPosition.M11,
            VesselPosition.M12,
            VesselPosition.M13,
            VesselPosition.M14,
            VesselPosition.M15,
            VesselPosition.M16,
            VesselPosition.M17,
            VesselPosition.M18,
            VesselPosition.M19,
            VesselPosition.M20,
            VesselPosition.M21,
            VesselPosition.M22,
            VesselPosition.M23,
            VesselPosition.M24,
            VesselPosition.N01,
            VesselPosition.N02,
            VesselPosition.N03,
            VesselPosition.N04,
            VesselPosition.N05,
            VesselPosition.N06,
            VesselPosition.N07,
            VesselPosition.N08,
            VesselPosition.N09,
            VesselPosition.N10,
            VesselPosition.N11,
            VesselPosition.N12,
            VesselPosition.N13,
            VesselPosition.N14,
            VesselPosition.N15,
            VesselPosition.N16,
            VesselPosition.N17,
            VesselPosition.N18,
            VesselPosition.N19,
            VesselPosition.N20,
            VesselPosition.N21,
            VesselPosition.N22,
            VesselPosition.N23,
            VesselPosition.N24,
            VesselPosition.O01,
            VesselPosition.O02,
            VesselPosition.O03,
            VesselPosition.O04,
            VesselPosition.O05,
            VesselPosition.O06,
            VesselPosition.O07,
            VesselPosition.O08,
            VesselPosition.O09,
            VesselPosition.O10,
            VesselPosition.O11,
            VesselPosition.O12,
            VesselPosition.O13,
            VesselPosition.O14,
            VesselPosition.O15,
            VesselPosition.O16,
            VesselPosition.O17,
            VesselPosition.O18,
            VesselPosition.O19,
            VesselPosition.O20,
            VesselPosition.O21,
            VesselPosition.O22,
            VesselPosition.O23,
            VesselPosition.O24,
            VesselPosition.P01,
            VesselPosition.P02,
            VesselPosition.P03,
            VesselPosition.P04,
            VesselPosition.P05,
            VesselPosition.P06,
            VesselPosition.P07,
            VesselPosition.P08,
            VesselPosition.P09,
            VesselPosition.P10,
            VesselPosition.P11,
            VesselPosition.P12,
            VesselPosition.P13,
            VesselPosition.P14,
            VesselPosition.P15,
            VesselPosition.P16,
            VesselPosition.P17,
            VesselPosition.P18,
            VesselPosition.P19,
            VesselPosition.P20,
            VesselPosition.P21,
            VesselPosition.P22,
            VesselPosition.P23,
            VesselPosition.P24)),
    // A row in an 8 wide Flipper rack
    ROWOF8("ROWOF8",Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A02,
            VesselPosition.A03,
            VesselPosition.A04,
            VesselPosition.A05,
            VesselPosition.A06,
            VesselPosition.A07,
            VesselPosition.A08)),
    // A row in two 12 x 8 Flipper racks
    ROWOF24("ROWOF24",Arrays.asList(
            VesselPosition.A01,
            VesselPosition.A02,
            VesselPosition.A03,
            VesselPosition.A04,
            VesselPosition.A05,
            VesselPosition.A06,
            VesselPosition.A07,
            VesselPosition.A08,
            VesselPosition.A09,
            VesselPosition.A10,
            VesselPosition.A11,
            VesselPosition.A12,
            VesselPosition.A13,
            VesselPosition.A14,
            VesselPosition.A15,
            VesselPosition.A16,
            VesselPosition.A17,
            VesselPosition.A18,
            VesselPosition.A19,
            VesselPosition.A20,
            VesselPosition.A21,
            VesselPosition.A22,
            VesselPosition.A23,
            VesselPosition.A24)),
    P96_24ROWSOF4_COLWISE_8TIP("P96_24ROWSOF4_COLWISE_8TIP",Arrays.asList(
            VesselPosition.A01,
            VesselPosition.I01,
            VesselPosition.Q01,
            VesselPosition.A02,
            VesselPosition.I02,
            VesselPosition.Q02,
            VesselPosition.A03,
            VesselPosition.I03,
            VesselPosition.Q03,
            VesselPosition.A04,
            VesselPosition.I04,
            VesselPosition.Q04,
            VesselPosition.B01,
            VesselPosition.J01,
            VesselPosition.R01,
            VesselPosition.B02,
            VesselPosition.J02,
            VesselPosition.R02,
            VesselPosition.B03,
            VesselPosition.J03,
            VesselPosition.R03,
            VesselPosition.B04,
            VesselPosition.J04,
            VesselPosition.R04,
            VesselPosition.C01,
            VesselPosition.K01,
            VesselPosition.S01,
            VesselPosition.C02,
            VesselPosition.K02,
            VesselPosition.S02,
            VesselPosition.C03,
            VesselPosition.K03,
            VesselPosition.S03,
            VesselPosition.C04,
            VesselPosition.K04,
            VesselPosition.S04,
            VesselPosition.D01,
            VesselPosition.L01,
            VesselPosition.T01,
            VesselPosition.D02,
            VesselPosition.L02,
            VesselPosition.T02,
            VesselPosition.D03,
            VesselPosition.L03,
            VesselPosition.T03,
            VesselPosition.D04,
            VesselPosition.L04,
            VesselPosition.T04,
            VesselPosition.E01,
            VesselPosition.M01,
            VesselPosition.U01,
            VesselPosition.E02,
            VesselPosition.M02,
            VesselPosition.U02,
            VesselPosition.E03,
            VesselPosition.M03,
            VesselPosition.U03,
            VesselPosition.E04,
            VesselPosition.M04,
            VesselPosition.U04,
            VesselPosition.F01,
            VesselPosition.N01,
            VesselPosition.V01,
            VesselPosition.F02,
            VesselPosition.N02,
            VesselPosition.V02,
            VesselPosition.F03,
            VesselPosition.N03,
            VesselPosition.V03,
            VesselPosition.F04,
            VesselPosition.N04,
            VesselPosition.V04,
            VesselPosition.G01,
            VesselPosition.O01,
            VesselPosition.W01,
            VesselPosition.G02,
            VesselPosition.O02,
            VesselPosition.W02,
            VesselPosition.G03,
            VesselPosition.O03,
            VesselPosition.W03,
            VesselPosition.G04,
            VesselPosition.O04,
            VesselPosition.W04,
            VesselPosition.H01,
            VesselPosition.P01,
            VesselPosition.X01,
            VesselPosition.H02,
            VesselPosition.P02,
            VesselPosition.X02,
            VesselPosition.H03,
            VesselPosition.P03,
            VesselPosition.X03,
            VesselPosition.H04,
            VesselPosition.P04,
            VesselPosition.X04
            )),
    // Single well sections
    A01("A01", Arrays.asList(VesselPosition.A01)),
    A02("A02", Arrays.asList(VesselPosition.A02)),
    A03("A03", Arrays.asList(VesselPosition.A03)),
    A04("A04", Arrays.asList(VesselPosition.A04)),
    A05("A05", Arrays.asList(VesselPosition.A05)),
    A06("A06", Arrays.asList(VesselPosition.A06)),
    A07("A07", Arrays.asList(VesselPosition.A07)),
    A08("A08", Arrays.asList(VesselPosition.A08)),
    A09("A09", Arrays.asList(VesselPosition.A09)),
    A10("A10", Arrays.asList(VesselPosition.A10)),
    A11("A11", Arrays.asList(VesselPosition.A11)),
    A12("A12", Arrays.asList(VesselPosition.A12)),
    B01("B01", Arrays.asList(VesselPosition.B01)),
    B02("B02", Arrays.asList(VesselPosition.B02)),
    B03("B03", Arrays.asList(VesselPosition.B03)),
    B04("B04", Arrays.asList(VesselPosition.B04)),
    B05("B05", Arrays.asList(VesselPosition.B05)),
    B06("B06", Arrays.asList(VesselPosition.B06)),
    B07("B07", Arrays.asList(VesselPosition.B07)),
    B08("B08", Arrays.asList(VesselPosition.B08)),
    B09("B09", Arrays.asList(VesselPosition.B09)),
    B10("B10", Arrays.asList(VesselPosition.B10)),
    B11("B11", Arrays.asList(VesselPosition.B11)),
    B12("B12", Arrays.asList(VesselPosition.B12)),
    C01("C01", Arrays.asList(VesselPosition.C01)),
    C02("C02", Arrays.asList(VesselPosition.C02)),
    C03("C03", Arrays.asList(VesselPosition.C03)),
    C04("C04", Arrays.asList(VesselPosition.C04)),
    C05("C05", Arrays.asList(VesselPosition.C05)),
    C06("C06", Arrays.asList(VesselPosition.C06)),
    C07("C07", Arrays.asList(VesselPosition.C07)),
    C08("C08", Arrays.asList(VesselPosition.C08)),
    C09("C09", Arrays.asList(VesselPosition.C09)),
    C10("C10", Arrays.asList(VesselPosition.C10)),
    C11("C11", Arrays.asList(VesselPosition.C11)),
    C12("C12", Arrays.asList(VesselPosition.C12)),
    D01("D01", Arrays.asList(VesselPosition.D01)),
    D02("D02", Arrays.asList(VesselPosition.D02)),
    D03("D03", Arrays.asList(VesselPosition.D03)),
    D04("D04", Arrays.asList(VesselPosition.D04)),
    D05("D05", Arrays.asList(VesselPosition.D05)),
    D06("D06", Arrays.asList(VesselPosition.D06)),
    D07("D07", Arrays.asList(VesselPosition.D07)),
    D08("D08", Arrays.asList(VesselPosition.D08)),
    D09("D09", Arrays.asList(VesselPosition.D09)),
    D10("D10", Arrays.asList(VesselPosition.D10)),
    D11("D11", Arrays.asList(VesselPosition.D11)),
    D12("D12", Arrays.asList(VesselPosition.D12)),
    E01("E01", Arrays.asList(VesselPosition.E01)),
    E02("E02", Arrays.asList(VesselPosition.E02)),
    E03("E03", Arrays.asList(VesselPosition.E03)),
    E04("E04", Arrays.asList(VesselPosition.E04)),
    E05("E05", Arrays.asList(VesselPosition.E05)),
    E06("E06", Arrays.asList(VesselPosition.E06)),
    E07("E07", Arrays.asList(VesselPosition.E07)),
    E08("E08", Arrays.asList(VesselPosition.E08)),
    E09("E09", Arrays.asList(VesselPosition.E09)),
    E10("E10", Arrays.asList(VesselPosition.E10)),
    E11("E11", Arrays.asList(VesselPosition.E11)),
    E12("E12", Arrays.asList(VesselPosition.E12)),
    F01("F01", Arrays.asList(VesselPosition.F01)),
    F02("F02", Arrays.asList(VesselPosition.F02)),
    F03("F03", Arrays.asList(VesselPosition.F03)),
    F04("F04", Arrays.asList(VesselPosition.F04)),
    F05("F05", Arrays.asList(VesselPosition.F05)),
    F06("F06", Arrays.asList(VesselPosition.F06)),
    F07("F07", Arrays.asList(VesselPosition.F07)),
    F08("F08", Arrays.asList(VesselPosition.F08)),
    F09("F09", Arrays.asList(VesselPosition.F09)),
    F10("F10", Arrays.asList(VesselPosition.F10)),
    F11("F11", Arrays.asList(VesselPosition.F11)),
    F12("F12", Arrays.asList(VesselPosition.F12)),
    G01("G01", Arrays.asList(VesselPosition.G01)),
    G02("G02", Arrays.asList(VesselPosition.G02)),
    G03("G03", Arrays.asList(VesselPosition.G03)),
    G04("G04", Arrays.asList(VesselPosition.G04)),
    G05("G05", Arrays.asList(VesselPosition.G05)),
    G06("G06", Arrays.asList(VesselPosition.G06)),
    G07("G07", Arrays.asList(VesselPosition.G07)),
    G08("G08", Arrays.asList(VesselPosition.G08)),
    G09("G09", Arrays.asList(VesselPosition.G09)),
    G10("G10", Arrays.asList(VesselPosition.G10)),
    G11("G11", Arrays.asList(VesselPosition.G11)),
    G12("G12", Arrays.asList(VesselPosition.G12)),
    H01("H01", Arrays.asList(VesselPosition.H01)),
    H02("H02", Arrays.asList(VesselPosition.H02)),
    H03("H03", Arrays.asList(VesselPosition.H03)),
    H04("H04", Arrays.asList(VesselPosition.H04)),
    H05("H05", Arrays.asList(VesselPosition.H05)),
    H06("H06", Arrays.asList(VesselPosition.H06)),
    H07("H07", Arrays.asList(VesselPosition.H07)),
    H08("H08", Arrays.asList(VesselPosition.H08)),
    H09("H09", Arrays.asList(VesselPosition.H09)),
    H10("H10", Arrays.asList(VesselPosition.H10)),
    H11("H11", Arrays.asList(VesselPosition.H11)),
    H12("H12", Arrays.asList(VesselPosition.H12)),
    ;

    private final String sectionName;
    private List<VesselPosition> wells = new ArrayList<>();
    private static Map<String, SBSSection> mapNameToSection = new HashMap<>();
    static {
        for (SBSSection sbsSection : SBSSection.values()) {
            mapNameToSection.put(sbsSection.getSectionName(), sbsSection);
        }
    }

    SBSSection(String sectionName, List<VesselPosition> wells) {
        this.sectionName = sectionName;
        this.wells = wells;
    }

    public String getSectionName() {
        return sectionName;
    }

    public List<VesselPosition> getWells() {
        return wells;
    }

    public static SBSSection getBySectionName(String sectionName) {
        SBSSection sbsSection = mapNameToSection.get(sectionName);
        if(sbsSection == null) {
            throw new RuntimeException("Failed to find section " + sectionName);
        }
        return sbsSection;
    }
}
