# External system definitions.  These describe the various deployments of external systems with which Mercury might
# integrate.

app:

    DEV:
      host:     localhost
      port:     8443
      jmsPort:  5445
      workflowValidationEmail:

    AUTO_BUILD:
      host:     crsp-dev-mercury.broadinstitute.org
      port:     8443
      jmsPort:  5446
      workflowValidationEmail:

    TEST:
      host:     crsp-dev-mercury.broadinstitute.org
      port:     8443
      jmsPort:  5445
      workflowValidationEmail:

    QA:
      host:     crsp-qa-mercury.broadinstitute.org
      port:     8443
      jmsPort:  5445
      workflowValidationEmail:

    RC:
      host:     crsp-rc-mercury.broadinstitute.org
      port:     8443
      jmsPort:  5447
      workflowValidationEmail:

    PROD:
      host:     crsp-mercury.broadinstitute.org
      port:     8443
      jmsPort:  5445
      workflowValidationEmail: gplims@broadinstitute.org
      #limsworkflowvalidation@broadinstitute.org

# Stubbed out so that the MercuryConfiguration doesn't throw a big fat exception and halts the Mercury WAR deployment.
bsp:

    DEV:
      login:    seqsystem
      password: bspbsp
      host:     crsp-dev-bsp.broadinstitute.org
      port:     8443

    RC:
      login:    seqsystem
      password: bspbsp
      host:     crsp-qa-bsp.broadinstitute.org
      port:     8443

    PROD:
      login:
      password:
      host:     crsp-bsp.broadinstitute.org
      port:

squid:
    DEV:
    QA:
    PROD:

datawhEtl:
    DEV:
    QA:
    PROD:

jira:

    TEST:
      login:    crspuser
      password: crspuser
      host:     crsptestjira.broadinstitute.org
      port:     8443
      urlBase:      https://crsptestjira.broadinstitute.org:8443

    QA:
      login:    crspuser
      password: crspuser
      host:     crsptestjira.broadinstitute.org
      port:     8443
      urlBase:  https://crspqajira.broadinstitute.org:8443


    PROD:
      login:
      password:
      host:     crspjira.broadinstitute.org
#      port:     8020
      urlBase:      https://crspjira.broadinstitute.org

portal:
    TEST:
      login:    portaluser
      password: Dr1ftw00d
      host:     crsp-dev-portal
      port:     8444

    DEV:
      login:    portaluser
      password: Dr1ftw00d
      host:     crsp-dev-portal
      port:     8444

    QA:
      login:    portaluser
      password: Dr1ftw00d
      host:     crsp-qa-portal
      port:     8444

    PROD:
      login:
      password:
      host:     crsp-portal
      port:

quote:

    DEV:
      login:    crspuser
      password: 880S4inyButton
      url:      http://quotedev:8080

    QA:
      login:    crspuser
      password: 880S4inyButton
      url:      http://quoteqa:8080

    PROD:
      login:
      password:
      url:      http://quoteprod:8080


thrift:

    QA:
      host: vsquidthriftserviceqa
      port: 9090

    TEST:
      host: prodinfobuild
      port: 9090

    PROD:
      host: seqlims
      port: 9090


# rename to wsMsgStore
deckMsgs:

    DEV:
        messageStoreDirRoot: /seq/lims/crspmercury/dev

    QA:
        messageStoreDirRoot: /seq/lims/crspmercury/qa

    PROD:
        messageStoreDirRoot: /seq/lims/crspmercury/prod


bettaLimsServer:

    DEV:
        wsHost: vbettalimsqa1
        wsPort: 9998
        #14009
        jmsHost: vbettalimsqa1
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.thompson

    TEST:
        wsHost: vbettalimsqa1
        wsPort: 9997
        jmsHost: vbettalimsqa1
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.test

    QA:
        wsHost: vbettalimsqa1
        wsPort: 9998
        jmsHost: vbettalimsqa1
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.qa

    PROD:
        wsHost: seqlims
        wsPort: 9998
        jmsHost: seqlims
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims

hipchat:
    DEV:
        baseUrl: https://www.hipchat.com/v1/rooms/message
        gpLimsRoom: GPLIMS Testing
        authorizationToken: db3e86c451ef8ac0cddb94133e0455

    QA:
        baseUrl: https://www.hipchat.com/v1/rooms/message
        gpLimsRoom: GPLIMS Testing
        authorizationToken: db3e86c451ef8ac0cddb94133e0455

    PROD:
        baseUrl: https://www.hipchat.com/v1/rooms/message
        gpLimsRoom: GPLims
        authorizationToken: db3e86c451ef8ac0cddb94133e0455

# Mercury configuration, this describes how Mercury deployments are connected to external system deployments.

mercury:

    DEV:

      app:      DEV
      bsp:      DEV
      portal:   DEV
      jira:     TEST
      quote:    QA
      squid:    DISABLED
      thrift:   TEST
      deckMsgs: DEV
      datawhEtl: DISABLED
      bettaLimsServer: DEV
      hipchat: DEV


    AUTO_BUILD:

      app:      AUTO_BUILD
      bsp:      DEV
      jira:     TEST
      quote:    QA
      squid:    DISABLED
      thrift:   TEST
      deckMsgs: DEV
      datawhEtl: DISABLED
      bettaLimsServer: DEV
      hipchat: DEV


    TEST:

      app:      TEST
      bsp:      DEV
      portal:   DEV
      jira:     TEST
      quote:    DEV
      squid:    DISABLED
      thrift:   TEST
      deckMsgs: DEV
      datawhEtl: DISABLED
      bettaLimsServer: TEST
      hipchat: DEV


    QA:

      app:      QA
      bsp:      RC
      portal:   QA
      jira:     QA
      quote:    QA
      squid:    DISABLED
      thrift:   QA
      deckMsgs: QA
      datawhEtl: DISABLED
      bettaLimsServer: QA
      hipchat: DEV


    RC:

      app:      RC
      bsp:      RC
      portal:   QA
      jira:     TEST
      quote:    QA
      squid:    DISABLED
      thrift:   QA
      deckMsgs: QA
      datawhEtl: DISABLED
      bettaLimsServer: QA
      hipchat: DEV


    PROD:

      app:      PROD
      bsp:      PROD
      portal:   PROD
      jira:     PROD
      quote:    PROD
      squid:    DISABLED
      thrift:   PROD
      deckMsgs: PROD
      datawhEtl: DISABLED
      bettaLimsServer: PROD
      hipchat: PROD
