# External system definitions.  These describe the various deployments of external systems with which Mercury might
# integrate.

app:

    DEV:
      host:     localhost
      port:     8080
      jmsPort:  5445
      workflowValidationEmail: andrew@broadinstitute.org

    AUTO_BUILD:
      host:     mercurydev.broadinstitute.org
      port:     8081
      jmsPort:  5446
      workflowValidationEmail: andrew@broadinstitute.org

    TEST:
      host:     crsp-dev-mercury.broadinstitute.org
      port:     8080
      jmsPort:  5445
      workflowValidationEmail: andrew@broadinstitute.org

    QA:
      host:     crsp-qa-mercury.broadinstitute.org
      port:     8081
      jmsPort:  5445
      workflowValidationEmail: smcdonou@broadinstitute.org

    RC:
      host:     mercuryrc.broadinstitute.org
      port:     8082
      jmsPort:  5447
      workflowValidationEmail: smcdonou@broadinstitute.org

    PROD:
      host:     crsp-mercury.broadinstitute.org
      jmsPort:  5445
      workflowValidationEmail: gplims@broadinstitute.org
      #limsworkflowvalidation@broadinstitute.org


bsp:

    DEV:
      login:    xxxx
      password: xxxx
      host:     xxxx
      port:     1

    QA:
      login:    xxxx
      password: xxxx
      host:     xxxx
      port:     1

    PROD:
      login:    xxxx
      password: xxxx
      host:     xxxx
      port:     1


gap:

    DEV:
      login:    xxxx
      password: xxxx
      url:      xxxx

    QA:
      login:    xxxx
      password: xxxx
      url:      xxxx

    PROD:
      login:    xxxx
      password: xxxx
      url:      xxxx


jira:

    TEST:
      login:    squid
      password: squid
      host:     crsptestjira.broadinstitute.org
      port:     8443
      urlBase:      https://crsptestjira.broadinstitute.org:8443

    PROD:
      login:    squid
      password: squid
      host:     crspjira.broadinstitute.org
#      port:     8020
      urlBase:      https://crspjira.broadinstitute.org

quote:

    DEV:
      login:    rnordin@broadinstitute.org
      password: Squ1d_us3r
      url:      http://quotedev:8080

    QA:
      login:    rnordin@broadinstitute.org
      password: Squ1d_us3r
      url:      http://quoteqa:8080

    PROD:
      login:    rnordin@broadinstitute.org
      password: Squ1d_us3r
      url:      http://quoteprod:8080



squid:

    DEV:
      url: http://localhost:8080/squid

    TEST:
      url: http://prodinfobuild.broadinstitute.org:8020/squid

    QA:
      url: http://vsquidrc.broadinstitute.org:8000/squid

    PROD:
      url: http://squid-ui.broadinstitute.org:8000/squid




thrift:

    QA:
      host: seqtest04
      port: 9090

    TEST:
      host: prodinfobuild
      port: 9090

    PROD:
      host: seqlims
      port: 9090


# rename to wsMsgStore
deckMsgs:

    DEV:
        messageStoreDirRoot: /seq/lims/mercury/dev

    QA:
        messageStoreDirRoot: /seq/lims/mercury/qa

    PROD:
        messageStoreDirRoot: /seq/lims/mercury/prod


bettaLimsServer:

    DEV:
        wsHost: node115
        wsPort: 9998
        #14009
        jmsHost: node115
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.thompson

    TEST:
        wsHost: node115
        wsPort: 9997
        jmsHost: node115
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.test

    QA:
        wsHost: vbettalimsqa
        wsPort: 9998
        jmsHost: node115
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.qa

    PROD:
        wsHost: seqlims
        wsPort: 9998
        jmsHost: seqlims
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims

datawhEtl:

    DEV:
        datawhEtlDirRoot: /seq/lims/datawh/dev

    QA:
        datawhEtlDirRoot: /seq/lims/datawh/qa

    PROD:
        datawhEtlDirRoot: /seq/lims/datawh/prod


hipchat:
    DEV:
        baseUrl: https://www.hipchat.com/v1/rooms/message
        gpLimsRoom: GPLIMS Testing
        authorizationToken: db3e86c451ef8ac0cddb94133e0455

    PROD:
        baseUrl: https://www.hipchat.com/v1/rooms/message
        gpLimsRoom: GPLims
        authorizationToken: db3e86c451ef8ac0cddb94133e0455

# Mercury configuration, this describes how Mercury deployments are connected to external system deployments.



mercury:

    DEV:

      app:      DEV
      bsp:      DEV
      gap:      DEV
      jira:     TEST
      quote:    QA
      squid:    DEV
      thrift:   QA
      deckMsgs: DEV
      datawhEtl: DEV
      bettaLimsServer: DEV
      tableau:  NOT_SUPPORTED
      hipchat: DEV


    AUTO_BUILD:

      app:      AUTO_BUILD
      bsp:      DEV
      gap:      DEV
      jira:     TEST
      quote:    QA
      squid:    DEV
      thrift:   QA
      deckMsgs: DEV
      datawhEtl: DEV
      bettaLimsServer: DEV
      tableau:  NOT_SUPPORTED
      hipchat: DEV


    TEST:

      app:      TEST
      bsp:      DEV
      gap:      DEV
      jira:     TEST
      quote:    DEV
      squid:    TEST
      thrift:   TEST
      deckMsgs: DEV
      datawhEtl: DEV
      bettaLimsServer: TEST
      tableau:  NOT_SUPPORTED
      hipchat: DEV


    QA:

      app:      QA
      bsp:      QA
      gap:      QA
      jira:     TEST
      quote:    QA
      squid:    QA
      thrift:   QA
      deckMsgs: QA
      datawhEtl: QA
      bettaLimsServer: QA
      tableau:  NOT_SUPPORTED
      hipchat: DEV


    RC:

      app:      RC
      bsp:      QA
      gap:      QA
      jira:     TEST
      quote:    QA
      squid:    QA
      thrift:   QA
      deckMsgs: QA
      datawhEtl: QA
      bettaLimsServer: QA
      tableau:  NOT_SUPPORTED
      hipchat: DEV


    PROD:

      app:      PROD
      bsp:      PROD
      gap:      PROD
      jira:     PROD
      quote:    PROD
      squid:    PROD
      thrift:   PROD
      deckMsgs: PROD
      datawhEtl: PROD
      bettaLimsServer: PROD
      tableau:  NOT_SUPPORTED
      hipchat: PROD