# External system definitions.  These describe the various deployments of external systems with which Mercury might
# integrate.

app:

    DEV:
      url:      http://localhost:8080/Mercury/

    TEST:
      url:      http://seq01.broadinstitute.org:8080/Mercury/

    QA:
      url:      http://pmbridgedev.broadinstitute.org:8081/Mercury/

    PROD:
      url:      http://mercury.broadinstitute.org/Mercury/

bsp:

    DEV:

      login:    seqsystem
      password: bspbsp
      host:     gapdev.broadinstitute.org
      port:     8080


    QA:

      login:    seqsystem
      password: bspbsp
      host:     gapqa.broadinstitute.org
      port:     8080


    PROD:

      login:    seqsystem
      password: bspbsp
      host:     bsp.broadinstitute.org
      port:     80


gap:

    DEV:

      login:    pmbridge
      password: bspbsp
      url:      http://gapdevanalysis.broadinstitute.org:8080


    QA:

      login:    pmbridge
      password: bspbsp
      url:      http://gapqaanalysis.broadinstitute.org:8080


    PROD:

      login:    pmbridge
      password: bspbsp
      url:      http://gapanalysis.broadinstitute.org:8080


jira:

    TEST:

      login:    squid
      password: squid
      host:     vsquid00.broadinstitute.org
      port:     8020
      urlBase:      http://vsquid00.broadinstitute.org:8020

    PROD:

      login:    squid
      password: squid
      host:     labopsjira.broadinstitute.org
#      port:     8020
      urlBase:      https://labopsjira.broadinstitute.org




pmbridge:

    DEV:

      url: http://pmbridgedev.broadinstitute.org/PMBridge


    PROD:

      url: http://pmbridge.broadinstitute.org/PMBridge




quote:

    QA:

      login:    rnordin@broadinstitute.org
      password: Squ1d_us3r
      url:      http://quoteqa:8080


    PROD:

      login:    rnordin@broadinstitute.org
      password: Squ1d_us3r
      url:      http://quoteprod:8080



squid:

    DEV:

      url: http://localhost:8080/squid


    TEST:

      url: http://vsquidrc.broadinstitute.org:8000/squid


    QA:

      url: http://vsquidrc.broadinstitute.org:8000/squid


    PROD:

      url: http://squid-ui.broadinstitute.org:8000/squid




thrift:

    QA:

      host: seqtest04
      port: 9090

    TEST:

      host: prodinfobuild
      port: 9090

    PROD:

      host: seqlims
      port: 9090



deckMsgs:

    DEV:

        messageStoreDirRoot: /seq/lims/mercury/dev
#        jmsHost:
#        jmsPort:
#        jmsQueue:

    QA:

        messageStoreDirRoot: /seq/lims/mercury/qa

    PROD:

        messageStoreDirRoot: /seq/lims/mercury/prod


datawhEtl:

    DEV:

        datawhEtlDirRoot: /seq/lims/datawh/dev

    QA:

        datawhEtlDirRoot: /seq/lims/datawh/qa

    PROD:

        datawhEtlDirRoot: /seq/lims/datawh/prod


# Mercury configuration, this describes how Mercury deployments are connected to external system deployments.



mercury:

    DEV:

      app:      DEV
      bsp:      DEV
      gap:      DEV
      jira:     TEST
      pmbridge: DEV
      quote:    QA
      squid:    DEV
      thrift:   QA
      deckMsgs: DEV
      datawhEtl: DEV


    TEST:

      app:      TEST
      bsp:      QA
      gap:      QA
      jira:     TEST
      pmbridge: DEV
      quote:    QA
      squid:    TEST
      thrift:   TEST
      deckMsgs: DEV
      datawhEtl: DEV

    QA:

      app:      QA
      bsp:      QA
      gap:      QA
      jira:     TEST
      pmbridge: DEV
      quote:    QA
      squid:    QA
      thrift:   QA
      deckMsgs: QA
      datawhEtl: QA


    RC:

      app:      QA
      bsp:      QA
      gap:      QA
      jira:     TEST
      pmbridge: DEV
      quote:    QA
      squid:    QA
      thrift:   QA
      deckMsgs: QA
      datawhEtl: QA


    PROD:

      app:      PROD
      bsp:      PROD
      gap:      PROD
      jira:     PROD
      pmbridge: PROD
      quote:    PROD
      squid:    PROD
      thrift:   PROD
      deckMsgs: PROD
      datawhEtl: PROD

