# External system definitions.  These describe the various deployments of external systems with which Mercury might
# integrate.

app:

    DEV:
      host:     localhost
      port:     8443
      jmsPort:  5445
      workflowValidationEmail:
      gpBillingManagers: !!set { Mercury-QA-Notifications@broadinstitute.org }

    AUTO_BUILD:
      host:     vmercurydev.broadinstitute.org
      port:     8443
      jmsPort:  5445
      workflowValidationEmail:
      gpBillingManagers: !!set { Mercury-QA-Notifications@broadinstitute.org }

    TEST:
      host:     mercuryfb.broadinstitute.org
      port:     8443
      jmsPort:  5445
      workflowValidationEmail:
      gpBillingManagers: !!set { Mercury-QA-Notifications@broadinstitute.org }
    QA:
      host:     mercuryqa.broadinstitute.org
      port:     8443
      jmsPort:  5445
      workflowValidationEmail:
      gpBillingManagers: !!set { Mercury-QA-Notifications@broadinstitute.org }

    RC:
      host:     mercuryrc.broadinstitute.org
      port:     8443
      jmsPort:  5445
      workflowValidationEmail:
      gpBillingManagers: !!set { Mercury-QA-Notifications@broadinstitute.org }

    PROD:
      host:     mercury.broadinstitute.org
      port:     8443
      jmsPort:  5445
      workflowValidationEmail: mercury-dev@broadinstitute.org
      #limsworkflowvalidation@broadinstitute.org
      gpBillingManagers: !!set { suhamil@broadinstitute.org, sferrier@broadinstitute.org }

bsp:

    DEV:
      login:    seqsystem
      password: bspbsp
      host:     gapdev.broadinstitute.org
      port:     8080

    RC:
      login:    seqsystem
      password: bspbsp
      host:     gaprc.broadinstitute.org
      port:     8080

    PROD:
      login:    seqsystem
      password: bspbsp
      host:     bsp.broadinstitute.org
      port:     80

gap:

    DEV:
      login:    seqsystem
      password: bspbsp
      host:     gapdev.broadinstitute.org
      port:     8080

    RC:
      login:    seqsystem
      password: bspbsp
      host:     gaprc.broadinstitute.org
      port:     8080

    PROD:
      login:    seqsystem
      password: bspbsp
      host:     gap.broadinstitute.org
      port:     80

jira:

    TEST:
      login:    squid
      password: squid
      host:     labopsjiratest.broadinstitute.org
      port:     8443
      urlBase:      https://labopsjiratest.broadinstitute.org:8443

    PROD:
      login:    squid
      password: squid
      host:     labopsjira.broadinstitute.org
#      port:     8020
      urlBase:      https://labopsjira.broadinstitute.org

collaborate:

    DEV:
      urlBase:      http://gpportal-dev:8080/portal/collaborate

    RC:
      urlBase:      http://gpportal-qa:8080/portal/collaborate

    PROD:
      urlBase:      http://gpportal-prod:8080/portal/collaborate


portal:

    TEST:
      urlBase:      http://gapdev:8111/portal

    DEV:
      urlBase:      http://gapdev:8111/portal

    QA:
      urlBase:      http://gaprc:8111/portal

    PROD:
      urlBase:      https://www.broadinstitute.org/portal

quote:

    TEST:
      login:    mercuryquote
      password: ml1m5qu0t3
      url:      https://quotes-test.broadinstitute.org

    PROD:
      login:    mercuryquote
      password: ml1m5qu0t3
      url:      http://quoteprod:8080


squid:

    DEV:
      url: http://localhost:8080/squid

    TEST:
      url: http://prodinfobuild.broadinstitute.org:8020/squid

    QA:
      url: http://vsquidrc1.broadinstitute.org:8000/squid

    PROD:
      url: http://squid-ui.broadinstitute.org:8000/squid


tableau:

    PROD:
      url: https://tableau.broadinstitute.org


thrift:

    QA:
      host: vsquidthriftserviceqa
      port: 9090

    TEST:
      host: prodinfobuild
      port: 9090

    PROD:
      host: vsquidthriftservice
      port: 9090


# rename to wsMsgStore
deckMsgs:

    DEV:
        messageStoreDirRoot: /seq/lims/mercury/dev

    QA:
        messageStoreDirRoot: /seq/lims/mercury/qa

    PROD:
        messageStoreDirRoot: /seq/lims/mercury/prod


bettaLimsServer:

    DEV:
        wsHost: vbettalimsqa1
        wsPort: 9997
        jmsHost: vbettalimsqa1
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.test

    TEST:
        wsHost: vbettalimsqa1
        wsPort: 9997
        jmsHost: vbettalimsqa1
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.test

    QA:
        wsHost: vbettalimsqa1
        wsPort: 9998
        jmsHost: vbettalimsqa1
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.qa

    PROD:
        wsHost: seqlims
        wsPort: 9998
        jmsHost: seqlims
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims

datawhEtl:

    DEV:
        datawhEtlDirRoot: /seq/lims/datawh/dev

    QA:
        datawhEtlDirRoot: /seq/lims/datawh/qa

    PROD:
        datawhEtlDirRoot: /seq/lims/datawh/prod

infiniumStarter:

    DEV:
        dataPath: /humgen/illumina_data/dev
#        dataPath: \\neon\humgen_illumina_data\dev
        minimumIdatFileLength: -1
        decodeDataPath: /humgen/illumina_decode_data/Decode_data/dev
#        decodeDataPath: \\neon\humgen_illumina_decode_data\Decode_data\dev
        archivePath: /tmp/gap_archive/infinium
        numChipsPerArchivePeriod: 10
        jmsHost: picard-jms-dev.broadinstitute.org
        jmsPort: 61616
        jmsQueue: broad.arrays.enqueue.staging
        login: mercury-pipeline
        passwordFileName: mercury-pipeline-dev-passwords.properties

    QA:
        dataPath: /humgen/illumina_data/qa
        minimumIdatFileLength: -1
        decodeDataPath: /humgen/illumina_decode_data/Decode_data/qa
        archivePath: /tmp/gap_archive/infinium
        numChipsPerArchivePeriod: 10
        jmsHost: picard-jms-dev.broadinstitute.org
        jmsPort: 61616
        jmsQueue: broad.arrays.enqueue.staging
        login: mercury-pipeline
        passwordFileName: mercury-pipeline-dev-passwords.properties

    PROD:
        dataPath: /humgen/illumina_data
        minimumIdatFileLength: 2000000
        decodeDataPath: /humgen/illumina_decode_data/Decode_data
        archivePath: /seq/tier3b/gap_archive/infinium
        numChipsPerArchivePeriod: 100
        jmsHost: picard-jms.broadinstitute.org
        jmsPort: 61616
        jmsQueue: broad.arrays.enqueue
        login: mercury-pipeline
        passwordFileName: mercury-pipeline-prod-passwords.properties

ddp:

    DEV:
        host: dsm-dev.datadonationplatform.org
        jwtSecretFilename: mercury-ddp-dev-secret.properties

    QA:
        host: dsm-dev.datadonationplatform.org
        jwtSecretFilename: mercury-ddp-qa-secret.properties

    PROD:
        host: dsm.datadonationplatform.org
        jwtSecretFilename: mercury-ddp-prod-secret.properties


decoder:

    DEV:
      host:     gp-decode-vm.broadinstitute.org
      port:     5000

    QA:
      host:     gp-decode-vm.broadinstitute.org
      port:     5000

    PROD:
      host:     gp-decode-vm.broadinstitute.org
      port:     5000

hipchat:
    DEV:
        baseUrl: https://www.hipchat.com/v1/rooms/message
        gpLimsRoom: GPLIMS Testing
        authorizationToken: db3e86c451ef8ac0cddb94133e0455

    PROD:
        baseUrl: https://www.hipchat.com/v1/rooms/message
        gpLimsRoom: Mercury & Athena (GPInfx)
        authorizationToken: db3e86c451ef8ac0cddb94133e0455

submission:
    DEV:
      host:     seqsubmission02
      port:     33333

    PROD:
      host:     seqsubmission01.broadinstitute.org
      port:     8080

sap:
    DEV:
      login:      GPCOMU
      password:   SAPERD300!
      sapSupportEmail: Mercury-QA-Notifications@broadinstitute.org
      sapSupportEmailSubjectPrefix: "TEST SAP Order"
    TEST:
      login:      GPCOMU
      password:   temp1!
      sapSupportEmail: Mercury-QA-Notifications@broadinstitute.org
      sapSupportEmailSubjectPrefix: "TEST SAP Order"
    QA:
      login:      GPCOMU
      password:   SAPERQ300!
      sapSupportEmail: Mercury-QA-Notifications@broadinstitute.org
      sapSupportEmailSubjectPrefix: "TEST SAP Order"
    RC:
      login:      GPCOMU
      password:   temp1!
      sapSupportEmail: Mercury-QA-Notifications@broadinstitute.org
      sapSupportEmailSubjectPrefix: "TEST SAP Order"
    PROD:
      login:      GPCOMU
      password:   SAPERP300!
      sapSupportEmail: BUSSYS@broadinstitute.org
      sapSupportEmailSubjectPrefix: "SAP Order"
# Mercury configuration, this describes how Mercury deployments are connected to external system deployments.
mercury:

    DEV:

      app:      DEV
      bsp:      DEV
      gap:      DEV
      jira:     TEST
      quote:    TEST
      squid:    TEST
      tableau:  PROD
      thrift:   TEST
      deckMsgs: DEV
      datawhEtl: DEV
      bettaLimsServer: DEV
      hipchat: DEV
      collaborate: DEV
      submission: DEV
      infiniumStarter: DEV
      sap:  RC
      decoder: DEV
      ddp: DEV


    AUTO_BUILD:

      app:      AUTO_BUILD
      bsp:      DEV
      gap:      DEV
      jira:     TEST
      quote:    TEST
      squid:    TEST
      tableau:  PROD
      thrift:   TEST
      deckMsgs: DEV
      datawhEtl: DEV
      bettaLimsServer: DEV
      hipchat: DEV
      collaborate: DEV
      submission: DEV
      infiniumStarter: DEV
      sap:  RC
      decoder: DEV
      ddp: DEV

    TEST:

      app:      TEST
      bsp:      DEV
      gap:      DEV
      jira:     TEST
      quote:    TEST
      squid:    TEST
      tableau:  PROD
      thrift:   TEST
      deckMsgs: DEV
      datawhEtl: DEV
      bettaLimsServer: TEST
      hipchat: DEV
      collaborate: DEV
      submission: DEV
      infiniumStarter: DEV
      sap:  RC
      decoder: DEV
      ddp: DEV

    QA:
      app:      QA
      bsp:      RC
      gap:      RC
      jira:     TEST
      quote:    TEST
      squid:    QA
      tableau:  PROD
      thrift:   QA
      deckMsgs: QA
      datawhEtl: QA
      bettaLimsServer: QA
      hipchat: DEV
      collaborate: RC
      submission: DEV
      infiniumStarter: QA
      sap:  RC
      decoder: QA
      ddp: QA

    RC:

      app:      RC
      bsp:      RC
      gap:      RC
      jira:     TEST
      quote:    TEST
      squid:    QA
      tableau:  PROD
      thrift:   QA
      deckMsgs: QA
      datawhEtl: QA
      bettaLimsServer: QA
      hipchat: DEV
      collaborate: RC
      submission: DEV
      infiniumStarter: QA
      sap:  RC
      decoder: QA
      ddp: QA


    PROD:

      app:      PROD
      bsp:      PROD
      gap:      PROD
      jira:     PROD
      quote:    PROD
      squid:    PROD
      tableau:  PROD
      thrift:   PROD
      deckMsgs: PROD
      datawhEtl: PROD
      bettaLimsServer: PROD
      hipchat: PROD
      collaborate: PROD
      submission: PROD
      infiniumStarter: PROD
      sap:  PROD
      decoder: PROD
      ddp: PROD

