# External system definitions.  These describe the various deployments of external systems with which Mercury might
# integrate.

app:

    DEV:
      host:     localhost
      port:     8080
      jmsPort:  5445
      workflowValidationEmail: andrew@broadinstitute.org

    AUTO_BUILD:
      host:     mercurydev.broadinstitute.org
      port:     8081
      jmsPort:  5446
      workflowValidationEmail: andrew@broadinstitute.org

    TEST:
      host:     mercurydev.broadinstitute.org
      port:     8080
      jmsPort:  5445
      workflowValidationEmail: andrew@broadinstitute.org

    QA:
      host:     mercuryqa.broadinstitute.org
      port:     8081
      jmsPort:  5445
      workflowValidationEmail: smcdonou@broadinstitute.org

    RC:
      host:     mercuryrc.broadinstitute.org
      port:     8082
      jmsPort:  5447
      workflowValidationEmail: smcdonou@broadinstitute.org

    PROD:
      host:     mercury.broadinstitute.org
      jmsPort:  5445
      workflowValidationEmail: gplims@broadinstitute.org
      #limsworkflowvalidation@broadinstitute.org

bsp:

    DEV:
      login:    seqsystem
      password: bspbsp
      host:     gapdev.broadinstitute.org
      port:     8080

    RC:
      login:    seqsystem
      password: bspbsp
      host:     gaprc.broadinstitute.org
      port:     8080

    PROD:
      login:    seqsystem
      password: bspbsp
      host:     bsp.broadinstitute.org
      port:     80


gap:

    DEV:
      login:    pmbridge
      password: bspbsp
      url:      http://gapdevanalysis.broadinstitute.org:8080

    QA:
      login:    pmbridge
      password: bspbsp
      url:      http://gapqaanalysis.broadinstitute.org:8080

    PROD:
      login:    pmbridge
      password: bspbsp
      url:      http://gapanalysis.broadinstitute.org:8080


jira:

    TEST:
      login:    squid
      password: squid
      host:     labopsjiratest.broadinstitute.org
      port:     8443
      urlBase:      https://labopsjiratest.broadinstitute.org:8443

    PROD:
      login:    squid
      password: squid
      host:     labopsjira.broadinstitute.org
#      port:     8020
      urlBase:      https://labopsjira.broadinstitute.org

quote:

    DEV:
      login:    rnordin@broadinstitute.org
      password: Squ1d_us3r
      url:      http://quotedev:8080

    QA:
      login:    rnordin@broadinstitute.org
      password: Squ1d_us3r
      url:      http://quoteqa:8080

    PROD:
      login:    rnordin@broadinstitute.org
      password: Squ1d_us3r
      url:      http://quoteprod:8080


squid:

    DEV:
      url: http://localhost:8080/squid

    TEST:
      url: http://prodinfobuild.broadinstitute.org:8020/squid

    QA:
      url: http://vsquidrc.broadinstitute.org:8000/squid

    PROD:
      url: http://squid-ui.broadinstitute.org:8000/squid




thrift:

    QA:
      host: seqtest04
      port: 9090

    TEST:
      host: prodinfobuild
      port: 9090

    PROD:
      host: seqlims
      port: 9090


# rename to wsMsgStore
deckMsgs:

    DEV:
        messageStoreDirRoot: /seq/lims/mercury/dev

    QA:
        messageStoreDirRoot: /seq/lims/mercury/qa

    PROD:
        messageStoreDirRoot: /seq/lims/mercury/prod


bettaLimsServer:

    DEV:
        wsHost: node115
        wsPort: 9998
        #14009
        jmsHost: node115
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.thompson

    TEST:
        wsHost: node115
        wsPort: 9997
        jmsHost: node115
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.test

    QA:
        wsHost: vbettalimsqa
        wsPort: 9998
        jmsHost: node115
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims.qa

    PROD:
        wsHost: seqlims
        wsPort: 9998
        jmsHost: seqlims
        jmsPort: 61616
        jmsQueue: broad.queue.bettalims

datawhEtl:

    DEV:
        datawhEtlDirRoot: /seq/lims/datawh/dev

    QA:
        datawhEtlDirRoot: /seq/lims/datawh/qa

    PROD:
        datawhEtlDirRoot: /seq/lims/datawh/prod


hipchat:
    DEV:
        baseUrl: https://www.hipchat.com/v1/rooms/message
        gpLimsRoom: GPLIMS Testing
        authorizationToken: db3e86c451ef8ac0cddb94133e0455

    PROD:
        baseUrl: https://www.hipchat.com/v1/rooms/message
        gpLimsRoom: GPLims
        authorizationToken: db3e86c451ef8ac0cddb94133e0455

# Mercury configuration, this describes how Mercury deployments are connected to external system deployments.


mercury:

    DEV:

      app:      DEV
      bsp:      DEV
      gap:      DEV
      jira:     TEST
      quote:    QA
      squid:    DEV
      thrift:   QA
      deckMsgs: DEV
      datawhEtl: DEV
      bettaLimsServer: DEV
      hipchat: DEV


    AUTO_BUILD:

      app:      AUTO_BUILD
      bsp:      DEV
      gap:      DEV
      jira:     TEST
      quote:    QA
      squid:    DEV
      thrift:   QA
      deckMsgs: DEV
      datawhEtl: DEV
      bettaLimsServer: DEV
      hipchat: DEV


    TEST:

      app:      TEST
      bsp:      DEV
      gap:      DEV
      jira:     TEST
      quote:    DEV
      squid:    TEST
      thrift:   TEST
      deckMsgs: DEV
      datawhEtl: DEV
      bettaLimsServer: TEST
      hipchat: DEV


    QA:

      app:      QA
      bsp:      RC
      gap:      QA
      jira:     TEST
      quote:    QA
      squid:    QA
      thrift:   QA
      deckMsgs: QA
      datawhEtl: QA
      bettaLimsServer: QA
      hipchat: DEV


    RC:

      app:      RC
      bsp:      RC
      gap:      QA
      jira:     TEST
      quote:    QA
      squid:    QA
      thrift:   QA
      deckMsgs: QA
      datawhEtl: QA
      bettaLimsServer: QA
      hipchat: DEV


    PROD:

      app:      PROD
      bsp:      PROD
      gap:      PROD
      jira:     PROD
      quote:    PROD
      squid:    PROD
      thrift:   PROD
      deckMsgs: PROD
      datawhEtl: PROD
      bettaLimsServer: PROD
      hipchat: PROD
