package org.broadinstitute.gpinformatics.mercury.boundary.vessel;

import org.broadinstitute.gpinformatics.infrastructure.test.DeploymentBuilder;
import org.broadinstitute.gpinformatics.infrastructure.test.TestGroups;
import org.broadinstitute.gpinformatics.mercury.control.dao.workflow.LabBatchDao;
import org.broadinstitute.gpinformatics.mercury.entity.workflow.LabBatch;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.testng.Arquillian;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.testng.Assert;
import org.testng.annotations.Test;

import javax.inject.Inject;
import java.util.ArrayList;

import static org.broadinstitute.gpinformatics.infrastructure.deployment.Deployment.DEV;

/**
 * Test creation of lab batches through the web service.
 */
@Test(groups = TestGroups.STANDARD)
public class LabBatchResourceTest extends Arquillian {
    @Inject
    private LabBatchResource labBatchResource;

    @Inject
    private LabBatchDao labBatchDao;

    @Deployment
    public static WebArchive buildMercuryWar() {
        return DeploymentBuilder.buildMercuryWar(DEV);
    }

    @Test
    public void testBasics() {
        LabBatchBean labBatchBean = new LabBatchBean();
        String batchId = "ARRAY-" + System.currentTimeMillis();
        labBatchBean.setBatchId(batchId);
        labBatchBean.setUsername("jowalsh");

        ArrayList<ChildVesselBean> childVesselBeans = new ArrayList<>();
        ChildVesselBean childVesselBean = new ChildVesselBean("SM-CT82G", "SM-CT82G", "Well [200uL]", "A01");
        childVesselBeans.add(childVesselBean);
        childVesselBean = new ChildVesselBean("SM-CT82H", "SM-CT82H", "Well [200uL]", "A02");
        childVesselBeans.add(childVesselBean);

        ParentVesselBean parentVesselBean = new ParentVesselBean("CO-19484878", null, "Plate 96 Well PCR [200ul]",
                childVesselBeans);
        labBatchBean.setParentVesselBean(parentVesselBean);
        labBatchBean.setWorkflowName("Infinium");
        labBatchResource.createLabBatch(labBatchBean);

        LabBatch labBatch = labBatchDao.findByBusinessKey(batchId);
        // Bucket entries never happen on these samples.
        // See PDO logic in LabBatchResource#createLabBatchByParentVessel - Product = PICO Only, PDO status = Completed
        Assert.assertEquals(labBatch.getBucketEntries().size(), 0);
        // Batch starting vessels do happen
        Assert.assertEquals(labBatch.getLabBatchStartingVessels().size(), 2);
    }

    String smIds = "SM-HAKGS\n"
                   + "SM-HAKGT\n"
                   + "SM-HAKGU\n"
                   + "SM-HAKGV\n"
                   + "SM-HAKGW\n"
                   + "SM-HAKGX\n"
                   + "SM-HAKGY\n"
                   + "SM-HAKGZ\n"
                   + "SM-HAKH1\n"
                   + "SM-HAKH2\n"
                   + "SM-HAKH3\n"
                   + "SM-HAKH4\n"
                   + "SM-HAKH5\n"
                   + "SM-HAKH6\n"
                   + "SM-HAKH7\n"
                   + "SM-HAKH8\n"
                   + "SM-HAKH9\n"
                   + "SM-HAKHA\n"
                   + "SM-HAKHB\n"
                   + "SM-HAKHC\n"
                   + "SM-HAKHD\n"
                   + "SM-HAKHE\n"
                   + "SM-HAKHF\n"
                   + "SM-HAKHG\n"
                   + "SM-HAKHH\n"
                   + "SM-HAKHI\n"
                   + "SM-HAKHJ\n"
                   + "SM-HAKHK\n"
                   + "SM-HAKHL\n"
                   + "SM-HAKHM\n"
                   + "SM-HAKHN\n"
                   + "SM-HAKHO\n"
                   + "SM-HAKHP\n"
                   + "SM-HAKHQ\n"
                   + "SM-HAKHR\n"
                   + "SM-HAKHS\n"
                   + "SM-HAKHT\n"
                   + "SM-HAKHU\n"
                   + "SM-HAKHV\n"
                   + "SM-HAKHW\n"
                   + "SM-HAKHX\n"
                   + "SM-HAKHY\n"
                   + "SM-HAKHZ\n"
                   + "SM-HAKI1\n"
                   + "SM-HAKI2\n"
                   + "SM-HAKI3\n"
                   + "SM-HAKI4\n"
                   + "SM-HAKI5\n"
                   + "SM-HAKI6\n"
                   + "SM-HAKI7\n"
                   + "SM-HAKI8\n"
                   + "SM-HAKI9\n"
                   + "SM-HAKIA\n"
                   + "SM-HAKIB\n"
                   + "SM-HAKIC\n"
                   + "SM-HAKID\n"
                   + "SM-HAKIE\n"
                   + "SM-HAKIF\n"
                   + "SM-HAKIG\n"
                   + "SM-HAKIH\n"
                   + "SM-HAKII\n"
                   + "SM-HAKIJ\n"
                   + "SM-HAKIK\n"
                   + "SM-HAKIL\n"
                   + "SM-HAKIM\n"
                   + "SM-HAKIN\n"
                   + "SM-HAKIO\n"
                   + "SM-HAKIP\n"
                   + "SM-HAKIQ\n"
                   + "SM-HAKIR\n"
                   + "SM-HAKIS\n"
                   + "SM-HAKIT\n"
                   + "SM-HAKIU\n"
                   + "SM-HAKIV\n"
                   + "SM-HAKIW\n"
                   + "SM-HAKIX\n"
                   + "SM-HAKIY\n"
                   + "SM-HAKIZ\n"
                   + "SM-HAKJ1\n"
                   + "SM-HAKJ2\n"
                   + "SM-HAKJ3\n"
                   + "SM-HAKJ4\n"
                   + "SM-HAKJ5\n"
                   + "SM-HAKJ6\n"
                   + "SM-HAKJ7\n"
                   + "SM-HAKJ8\n"
                   + "SM-HAKJ9\n"
                   + "SM-HAKJA\n"
                   + "SM-HAKJB\n"
                   + "SM-HAKJC\n"
                   + "SM-HAKJD\n"
                   + "SM-HAKJE\n"
                   + "SM-HAKJF\n"
                   + "SM-HAKJG\n"
                   + "SM-HAKJH\n"
                   + "SM-HAKJI\n"
                   + "SM-HAJVU\n"
                   + "SM-HAJVV\n"
                   + "SM-HAJVW\n"
                   + "SM-HAJVX\n"
                   + "SM-HAJVY\n"
                   + "SM-HAJVZ\n"
                   + "SM-HAJW1\n"
                   + "SM-HAJW2\n"
                   + "SM-HAJW3\n"
                   + "SM-HAJW4\n"
                   + "SM-HAJW5\n"
                   + "SM-HAJW6\n"
                   + "SM-HAJW7\n"
                   + "SM-HAJW8\n"
                   + "SM-HAJW9\n"
                   + "SM-HAJWA\n"
                   + "SM-HAJWB\n"
                   + "SM-HAJWC\n"
                   + "SM-HAJWD\n"
                   + "SM-HAJWE\n"
                   + "SM-HAJWF\n"
                   + "SM-HAJWG\n"
                   + "SM-HAJWH\n"
                   + "SM-HAJWI\n"
                   + "SM-HAJWJ\n"
                   + "SM-HAJWK\n"
                   + "SM-HAJWL\n"
                   + "SM-HAJWM\n"
                   + "SM-HAJWN\n"
                   + "SM-HAJWO\n"
                   + "SM-HAJWP\n"
                   + "SM-HAJWQ\n"
                   + "SM-HAJWR\n"
                   + "SM-HAJWS\n"
                   + "SM-HAJWT\n"
                   + "SM-HAJWU\n"
                   + "SM-HAJWV\n"
                   + "SM-HAJWW\n"
                   + "SM-HAJWX\n"
                   + "SM-HAJWY\n"
                   + "SM-HAJWZ\n"
                   + "SM-HAJX1\n"
                   + "SM-HAJX2\n"
                   + "SM-HAJX3\n"
                   + "SM-HAJX4\n"
                   + "SM-HAJX5\n"
                   + "SM-HAJX6\n"
                   + "SM-HAJX7\n"
                   + "SM-HAJX8\n"
                   + "SM-HAJX9\n"
                   + "SM-HAJXA\n"
                   + "SM-HAJXB\n"
                   + "SM-HAJXC\n"
                   + "SM-HAJXD\n"
                   + "SM-HAJXE\n"
                   + "SM-HAJXF\n"
                   + "SM-HAJXG\n"
                   + "SM-HAJXH\n"
                   + "SM-HAJXI\n"
                   + "SM-HAJXJ\n"
                   + "SM-HAJXK\n"
                   + "SM-HAJXL\n"
                   + "SM-HAJXM\n"
                   + "SM-HAJXN\n"
                   + "SM-HAJXO\n"
                   + "SM-HAJXP\n"
                   + "SM-HAJXQ\n"
                   + "SM-HAJXR\n"
                   + "SM-HAJXS\n"
                   + "SM-HAJXT\n"
                   + "SM-HAJXU\n"
                   + "SM-HAJXV\n"
                   + "SM-HAJXW\n"
                   + "SM-HAJXX\n"
                   + "SM-HAJXY\n"
                   + "SM-HAJXZ\n"
                   + "SM-HAJY1\n"
                   + "SM-HAJY2\n"
                   + "SM-HAJY3\n"
                   + "SM-HAJY4\n"
                   + "SM-HAJY5\n"
                   + "SM-HAJY6\n"
                   + "SM-HAJY7\n"
                   + "SM-HAJY8\n"
                   + "SM-HAJY9\n"
                   + "SM-HAJYA\n"
                   + "SM-HAJYB\n"
                   + "SM-HAJYC\n"
                   + "SM-HAJYD\n"
                   + "SM-HAJYE\n"
                   + "SM-HAJYF\n"
                   + "SM-HAJYG\n"
                   + "SM-HAJYH\n"
                   + "SM-HAJYI\n"
                   + "SM-HAJYJ\n"
                   + "SM-HAJYK\n"
                   + "SM-HAJ1D\n"
                   + "SM-HAJ1E\n"
                   + "SM-HAJ1F\n"
                   + "SM-HAJ1G\n"
                   + "SM-HAJ1H\n"
                   + "SM-HAJ1I\n"
                   + "SM-HAJ1J\n"
                   + "SM-HAJ1K\n"
                   + "SM-HAJ1L\n"
                   + "SM-HAJ1M\n"
                   + "SM-HAJ1N\n"
                   + "SM-HAJ1O\n"
                   + "SM-HAJ1P\n"
                   + "SM-HAJ1Q\n"
                   + "SM-HAJ1R\n"
                   + "SM-HAJ1S\n"
                   + "SM-HAJ1T\n"
                   + "SM-HAJ1U\n"
                   + "SM-HAJ1V\n"
                   + "SM-HAJ1X\n"
                   + "SM-HAJ1Y\n"
                   + "SM-HAJ1Z\n"
                   + "SM-HAJ21\n"
                   + "SM-HAJ22\n"
                   + "SM-HAJ23\n"
                   + "SM-HAJ25\n"
                   + "SM-HAJ26\n"
                   + "SM-HAJ27\n"
                   + "SM-HAJ28\n"
                   + "SM-HAJ29\n"
                   + "SM-HAJ2A\n"
                   + "SM-HAJ2B\n"
                   + "SM-HAJ2C\n"
                   + "SM-HAJ2E\n"
                   + "SM-HAJ2F\n"
                   + "SM-HAJ2G\n"
                   + "SM-HAJ2H\n"
                   + "SM-HAJ2I\n"
                   + "SM-HAJ2J\n"
                   + "SM-HAJ2K\n"
                   + "SM-HAJ2L\n"
                   + "SM-HAJ2N\n"
                   + "SM-HAJ2O\n"
                   + "SM-HAJ2P\n"
                   + "SM-HAJ2Q\n"
                   + "SM-HAJ2R\n"
                   + "SM-HAJ2S\n"
                   + "SM-HAJ2T\n"
                   + "SM-HAJ2U\n"
                   + "SM-HAJ2V\n"
                   + "SM-HAJ2W\n"
                   + "SM-HAJ2X\n"
                   + "SM-HAJ2Y\n"
                   + "SM-HAJ2Z\n"
                   + "SM-HAJ31\n"
                   + "SM-HAJ32\n"
                   + "SM-HAJ33\n"
                   + "SM-HAJ34\n"
                   + "SM-HAJ35\n"
                   + "SM-HAJ36\n"
                   + "SM-HAJ37\n"
                   + "SM-HAJ38\n"
                   + "SM-HAJ39\n"
                   + "SM-HAJ3A\n"
                   + "SM-HAJ3B\n"
                   + "SM-HAJ3C\n"
                   + "SM-HAJ3D\n"
                   + "SM-HAJ3E\n"
                   + "SM-HAJ3F\n"
                   + "SM-HAJ3G\n"
                   + "SM-HAJ3H\n"
                   + "SM-HAJ3I\n"
                   + "SM-HAJ3J\n"
                   + "SM-HAJ3K\n"
                   + "SM-HAJ3L\n"
                   + "SM-HAJ3M\n"
                   + "SM-HAJ3N\n"
                   + "SM-HAJ3O\n"
                   + "SM-HAJ3P\n"
                   + "SM-HAJ3Q\n"
                   + "SM-HAJ3R\n"
                   + "SM-HAJ3S\n"
                   + "SM-HAJ3T\n"
                   + "SM-HAJ3U\n"
                   + "SM-HAJ3V\n"
                   + "SM-HAJ3W\n"
                   + "SM-HAJ3X\n"
                   + "SM-HAJ3Y\n"
                   + "SM-HAJ3Z\n"
                   + "SM-HAJ41\n"
                   + "SM-HAJ42\n"
                   + "SM-HAJ43\n"
                   + "SM-HAJ44\n"
                   + "SM-HAJ45\n"
                   + "SM-HAJ46\n"
                   + "SM-HAJ47\n"
                   + "SM-HAHTL\n"
                   + "SM-HAHTM\n"
                   + "SM-HAHTN\n"
                   + "SM-HAHTO\n"
                   + "SM-HAHTP\n"
                   + "SM-HAHTQ\n"
                   + "SM-HAHTR\n"
                   + "SM-HAHTS\n"
                   + "SM-HAHTT\n"
                   + "SM-HAHTU\n"
                   + "SM-HAHTV\n"
                   + "SM-HAHTW\n"
                   + "SM-HAHTX\n"
                   + "SM-HAHTY\n"
                   + "SM-HAHTZ\n"
                   + "SM-HAHU1\n"
                   + "SM-HAHU2\n"
                   + "SM-HAHU3\n"
                   + "SM-HAHU4\n"
                   + "SM-HAHU5\n"
                   + "SM-HAHU6\n"
                   + "SM-HAHU7\n"
                   + "SM-HAHU8\n"
                   + "SM-HAHU9\n"
                   + "SM-HAHUA\n"
                   + "SM-HAHUB\n"
                   + "SM-HAHUC\n"
                   + "SM-HAHUD\n"
                   + "SM-HAHUE\n"
                   + "SM-HAHUF\n"
                   + "SM-HAHUG\n"
                   + "SM-HAHUH\n"
                   + "SM-HAHUI\n"
                   + "SM-HAHUJ\n"
                   + "SM-HAHUK\n"
                   + "SM-HAHUL\n"
                   + "SM-HAHUM\n"
                   + "SM-HAHUN\n"
                   + "SM-HAHUO\n"
                   + "SM-HAHUP\n"
                   + "SM-HAHUQ\n"
                   + "SM-HAHUR\n"
                   + "SM-HAHUS\n"
                   + "SM-HAHUT\n"
                   + "SM-HAHUU\n"
                   + "SM-HAHUV\n"
                   + "SM-HAHUW\n"
                   + "SM-HAHUX\n"
                   + "SM-HAHUY\n"
                   + "SM-HAHUZ\n"
                   + "SM-HAHV1\n"
                   + "SM-HAHV2\n"
                   + "SM-HAHV3\n"
                   + "SM-HAHV4\n"
                   + "SM-HAHV5\n"
                   + "SM-HAHV6\n"
                   + "SM-HAHV7\n"
                   + "SM-HAHV8\n"
                   + "SM-HAHV9\n"
                   + "SM-HAHVA\n"
                   + "SM-HAHVB\n"
                   + "SM-HAHVC\n"
                   + "SM-HAHVD\n"
                   + "SM-HAHVE\n"
                   + "SM-HAHVF\n"
                   + "SM-HAHVG\n"
                   + "SM-HAHVH\n"
                   + "SM-HAHVI\n"
                   + "SM-HAHVJ\n"
                   + "SM-HAHVK\n"
                   + "SM-HAHVL\n"
                   + "SM-HAHVM\n"
                   + "SM-HAHVN\n"
                   + "SM-HAHVO\n"
                   + "SM-HAHVP\n"
                   + "SM-HAHVQ\n"
                   + "SM-HAHVR\n"
                   + "SM-HAHVS\n"
                   + "SM-HAHVT\n"
                   + "SM-HAHVU\n"
                   + "SM-HAHVV\n"
                   + "SM-HAHVW\n"
                   + "SM-HAHVX\n"
                   + "SM-HAHVY\n"
                   + "SM-HAHVZ\n"
                   + "SM-HAHW1\n"
                   + "SM-HAHW2\n"
                   + "SM-HAHW3\n"
                   + "SM-HAHW4\n"
                   + "SM-HAHW5\n"
                   + "SM-HAHW6\n"
                   + "SM-HAHW7\n"
                   + "SM-HAHW8\n"
                   + "SM-HAHW9\n"
                   + "SM-HAHWA\n"
                   + "SM-HAHWB";

    @Test
    public void testCole() {
        LabBatchBean labBatchBean = new LabBatchBean();
        String batchId = "LCSET-" + System.currentTimeMillis();
        labBatchBean.setBatchId(batchId);
        labBatchBean.setUsername("jowalsh");

        ArrayList<ChildVesselBean> childVesselBeans = new ArrayList<>();
        ChildVesselBean childVesselBean = new ChildVesselBean("SM-CT82G", "SM-CT82G", "Well [200uL]", "A01");
        childVesselBeans.add(childVesselBean);
        childVesselBean = new ChildVesselBean("SM-CT82H", "SM-CT82H", "Well [200uL]", "A02");
        childVesselBeans.add(childVesselBean);

        ParentVesselBean parentVesselBean = new ParentVesselBean("CO-19484878", null, "Plate 96 Well PCR [200ul]",
                childVesselBeans);
        labBatchBean.setParentVesselBean(parentVesselBean);
        labBatchResource.createLabBatch(labBatchBean);

        LabBatch labBatch = labBatchDao.findByBusinessKey(batchId);
        Assert.assertEquals(labBatch.getBucketEntries().size(), 2);
    }
}