package org.broadinstitute.gpinformatics.mercury.entity.analysis.fixup;

import org.broadinstitute.gpinformatics.athena.control.dao.products.ProductDao;
import org.broadinstitute.gpinformatics.athena.entity.products.Product;
import org.broadinstitute.gpinformatics.infrastructure.test.DeploymentBuilder;
import org.broadinstitute.gpinformatics.infrastructure.test.TestGroups;
import org.broadinstitute.gpinformatics.mercury.boundary.analysis.AnalysisEjb;
import org.broadinstitute.gpinformatics.mercury.control.dao.analysis.AnalysisTypeDao;
import org.broadinstitute.gpinformatics.mercury.entity.analysis.AnalysisType;
import org.broadinstitute.gpinformatics.mercury.entity.envers.FixupCommentary;
import org.broadinstitute.gpinformatics.mercury.entity.reagent.ReagentDesign;
import org.broadinstitute.gpinformatics.mercury.entity.workflow.Workflow;
import org.broadinstitute.gpinformatics.mercury.presentation.UserBean;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.testng.Arquillian;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.testng.annotations.Test;
import javax.inject.Inject;

import java.util.List;

import static org.broadinstitute.gpinformatics.infrastructure.deployment.Deployment.DEV;
import static org.hamcrest.Matchers.nullValue;
import static org.hamcrest.MatcherAssert.assertThat;

@Test(groups = TestGroups.FIXUP)
public class AnalysisFixupTest extends Arquillian {

    @Inject
    private UserBean userBean;

    @Inject
    private AnalysisEjb analysisEjb;

    @Inject
    private ProductDao productDao;

    @Inject
    private AnalysisTypeDao analysisTypeDao;

    // Use (RC, "rc"), (PROD, "prod") to push the backfill to RC and production respectively.
    @Deployment
    public static WebArchive buildMercuryWar() {
        return DeploymentBuilder.buildMercuryWar(DEV, "dev");
    }

    /**
     * This script loads the initial data for the analysis pipeline lists.
     */
    @Test(enabled = false)
    public void initializeAnalysisTypes() {
        // Add the analysis types
        analysisEjb.addAnalysisType("AssemblyWithoutReference");
        analysisEjb.addAnalysisType("AssemblyWithReference");
        analysisEjb.addAnalysisType("Resequencing");
        analysisEjb.addAnalysisType("Control");
        analysisEjb.addAnalysisType("MetaGenomics");
    }

    @Test(enabled = false)
    public void initializeAligners() {
        // Add the aligners
        analysisEjb.addAligner("bwa");
        analysisEjb.addAligner("maq");
    }

    @Test(enabled = false)
    public void initializeReagent() {
        // Add the baits
        analysisEjb.addReagentDesign("1kg_sureselect_beta", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("altshuler_t2d_535genes_july2010", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("antigen_discovery", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("bpscz_500genes_may2010", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("cancer_cdna_500_cds", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("cancer_cdna_500_full_redesign", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("cancer_cpg_bspp_v1", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("cancer_cpg_island_v1", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("canine_3.1_nimblegen", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("canine_ca_oes_nimblegen", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("canine_ca_scottie_nimblegen", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("canine_exome_ea", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("canine_hcsma_nimblegen", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("canine_jrd_amy_hyp_nimblegen", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("canine_lymphoma_nimblegen", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("challenge_lipids_1000genes_may2010", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("ciliopathies_900_genes", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("daly_1kg_phase1validation_march2012", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("daly_autism_46genes_shift170", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("daly_gwaseq_ibd_redesign2_august2011", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("debakker_mhc_region_apr2011", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("dgi_metabolic_traits_lipid_genes", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("ebert_mds_december2010_17genes", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("ebert_mds_december2010_17genes_agilent", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("ebert_mds_december2010_33genes", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("ebert_mds_december2010_33genes_agilent", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("erlich_custom_1-6.28K_december2012", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("esophageal_cancer_500_genes", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("exome_plus_v1", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("exome_plus_v2", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("ferret_nimblegen", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("fhs_jhs_pilot", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("fisher_7genedev_september2011", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("flexgen_test", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("flexgen_test_redesign", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("FLUIDCTC", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("fluidigm_cll_drive", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("fluidigm_cll_trios", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("fluidigm_esoph", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("fluidigm_lung_drive", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("fluidigm_mouse_snp", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("gabriel_head-and-neck_4k-targets_december2010", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("gabriel_jhs_216genes_june2011", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("gabriel_tcga_lusc_validation_76genes_june2011", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("gabriel_tcga_ovarian_validation_july2010", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("glgc_lipid_extremes", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("halo_genomics_demo_kit", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("haloplex_cancer_7genes", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hard_to_capture_exome_regions_d1", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hard_to_capture_exome_regions_d2", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hard_to_capture_exome_regions_d3", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hard_to_capture_exome_regions_d4", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hard_to_capture_exome_regions_d5", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hard_to_capture_exome_regions_d6", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hard_to_capture_exome_regions_d7", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hard_to_capture_exome_regions_d8", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hard_to_capture_exome_regions_d9", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hirschhorn_bmi_extremes_1190genes_july2010", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hirschhorn_height_extremes_1078genes_july2010", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("hiv_elite_controllers_custom_sureselect", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("huang_prostatecancer_v1_january2013", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("ibd_gwaseq_design_2", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("kathiresan_mi_1125genes_nov2010", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("linblad-toh_dog_ocd", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("linblad-toh_human_ocd_13mb", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("MCKD1_interval_shift40_norepeat40", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("mml_10k_genes", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("mml_mmrc_8k", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("mouse_enu_mutant_discovery_exonic_redesign", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("mouse_mutation_discovery_part2", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("mouse_whole_exome_agilent_v1", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("mouse_whole_exome_agilent_v1_rebalanced", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("NewtonCheh_NatPepMDC_12genes3regions_Sep2011", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("Nimblegen_7_Gene_Tgts", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("Nimblegen_T2D_Tgts", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("novartis_ncle_1000_genes", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("novartis_ncle_1650_genes", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("oncomap_genes_shift170", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("pfizer_t2d_mi_exons", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("pkraft_brca-gwaseq_002", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("plasmodium_snps_and_exons", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("selector_test1", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("sureselectXT_Human_Methyl-Seq", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_agilent_1.1_refseq_plus_3_boosters", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_agilent_65mb", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_agilent_designed_120", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_agilent_plus_tcga_6k", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_agilent_sureselect_50mb", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_agilent_v3a", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_agilent_v3b", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_agilent_v3c", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_agilent_v5beta_no_rescue", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_agilent_v5beta_with_rescues", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_illumina_coding_v1", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_illumina_truseq_v1", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_refseq_coding", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("whole_exome_unique_gc_sorted", ReagentDesign.ReagentType.BAIT);
        analysisEjb.addReagentDesign("Yeast_Chr3_HiC_March_20_2008_v1_combined", ReagentDesign.ReagentType.BAIT);
    }

    @Test(enabled = false)
    public void initializeReferenceSequence() {
        // Add all the reference sequences
        analysisEjb.addReferenceSequence("454_B_adapter", "0", true);
        analysisEjb.addReferenceSequence("454_B_adapter", "-1", false);
        analysisEjb.addReferenceSequence("454_blue_heron_test_sequences", "0", true);
        analysisEjb.addReferenceSequence("454_blue_heron_test_sequences", "-1", false);
        analysisEjb.addReferenceSequence("454_test_sequences", "1", true);
        analysisEjb.addReferenceSequence("454_test_sequences", "0", false);
        analysisEjb.addReferenceSequence("454_test_sequences", "-1", false);
        analysisEjb.addReferenceSequence("Acidaminococcus_fermentans_DSM_20731", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_1656-2", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_1656-2_plasmids_ABKp1_ABKp2", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_AB0057", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_AB0057_plasmid_pAB0057", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_AB307-0294", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_ACICU", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_ACICU_plasmids_pACICU1_pACICU2", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_ATCC_17978_plasmids_pAB1_pAB2", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_AYE", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_AYE_plasmids_p1ABAYE_p2ABAYE_p3ABAYE_p4ABAYE", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_MDR-TJ", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_MDR-TJ_plasmid_pABTJ1", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_MDR-ZJ06", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_MDR-ZJ06_plasmid_pMDR-ZJ06", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_SDF", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_SDF_plasmids_p1ABSDF_p2ABSDF_p3ABSDF", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_TCDC-AB0715", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_baumannii_TCDC-AB0715_plasmids_p1ABTCDC0715_p2ABTCDC0715", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_calcoaceticus_PHEA-2", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_lwoffii_WJ10621", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_oleivorans_DR1", "0", true);
        analysisEjb.addReferenceSequence("Acinetobacter_sp_ADP1", "0", true);
        analysisEjb.addReferenceSequence("Actinomyces_odontolyticus_ATCC_17982", "0", true);
        analysisEjb.addReferenceSequence("Aeromonas_veronii_B565", "0", true);
        analysisEjb.addReferenceSequence("Afipia_sp_1NLS2", "0", true);
        analysisEjb.addReferenceSequence("Aggregatibacter_aphrophilus_F0387", "0", true);
        analysisEjb.addReferenceSequence("Ajellomyces_capsulatus_NAm1", "0", true);
        analysisEjb.addReferenceSequence("Algoriphagus_sp_PR1", "0", true);
        analysisEjb.addReferenceSequence("Alistipes_putredinis_DSM_17216", "0", true);
        analysisEjb.addReferenceSequence("Allomyces_macrogynus_ATCC_38327_with_mitochondria", "0", true);
        analysisEjb.addReferenceSequence("Anaerostipes_caccae_DSM_14662", "0", true);
        analysisEjb.addReferenceSequence("Anncallia_algerae_human_isolate", "0", true);
        analysisEjb.addReferenceSequence("Anncallia_algerae_insect_isolate", "0", true);
        analysisEjb.addReferenceSequence("Anolis_carolinensis", "0", true);
        analysisEjb.addReferenceSequence("Anopheles_gambiae_assemblyP3", "0", true);
        analysisEjb.addReferenceSequence("Antonospora_locustae", "0", true);
        analysisEjb.addReferenceSequence("Aplysia_californica", "1", true);
        analysisEjb.addReferenceSequence("Aplysia_californica", "-1", false);
        analysisEjb.addReferenceSequence("Aplysia_californica", "0", false);
        analysisEjb.addReferenceSequence("Arabidopsis_thaliana_microRNAs", "0", true);
        analysisEjb.addReferenceSequence("Arabidopsis_thaliana_microRNAs", "-1", false);
        analysisEjb.addReferenceSequence("Atopobium_rimae_ATCC_49626", "0", true);
        analysisEjb.addReferenceSequence("Bacillus_cereus_E33L", "0", true);
        analysisEjb.addReferenceSequence("Bacillus_cereus_G9842", "0", true);
        analysisEjb.addReferenceSequence("Bacillus_licheniformis_ATCC_14580", "0", true);
        analysisEjb.addReferenceSequence("Bacillus_sp._NRRL_B-14911", "0", true);
        analysisEjb.addReferenceSequence("Bacteroides_capillosus_ATCC_29799", "0", true);
        analysisEjb.addReferenceSequence("Bacteroides_dorei_5_1_36-D4", "0", true);
        analysisEjb.addReferenceSequence("Bacteroides_eggerthii_DSM_20697", "0", true);
        analysisEjb.addReferenceSequence("Bacteroides_fragilis_NCTC_9343", "0", true);
        analysisEjb.addReferenceSequence("Bacteroides_ovatus_ATCC_8483", "0", true);
        analysisEjb.addReferenceSequence("Bacteroides_thetaiotaomicron_VPI-5482_plasmid_p5482", "0", true);
        analysisEjb.addReferenceSequence("Bacteroides_uniformis_ATCC_8492", "0", true);
        analysisEjb.addReferenceSequence("Bartonella_tribocorum_CIP_105476", "0", true);
        analysisEjb.addReferenceSequence("Batrachochytrium_dendrobatidis_JEL423", "0", true);
        analysisEjb.addReferenceSequence("Bifidobacterium_bifidum_NCIMB_41171", "0", true);
        analysisEjb.addReferenceSequence("Bifidobacterium_longum_NCC2705_plasmid_pBLO1", "0", true);
        analysisEjb.addReferenceSequence("Bifidobacterium_longum_subsp_infantis_ATCC_15697", "0", true);
        analysisEjb.addReferenceSequence("Bilophila_wadsworthia_3_1_6", "0", false);
        analysisEjb.addReferenceSequence("Bilophila_wadsworthia_3_1_6", "1", true);
        analysisEjb.addReferenceSequence("Blastomyces_dermatitidis_ER-3", "0", true);
        analysisEjb.addReferenceSequence("Blautia_hansenii_DSM_20583", "0", true);
        analysisEjb.addReferenceSequence("Borrelia_burgdorferi_B31", "0", true);
        analysisEjb.addReferenceSequence("Borrelia_burgdorferi_B31", "-1", false);
        analysisEjb.addReferenceSequence("Borrelia_burgdorferi_B31_plasmid_cp26", "-1", false);
        analysisEjb.addReferenceSequence("Borrelia_burgdorferi_B31_plasmid_cp26", "0", true);
        analysisEjb.addReferenceSequence("Brucella_abortus_biovar1_str9-941", "0", true);
        analysisEjb.addReferenceSequence("Brucella_melitensis_16M", "0", true);
        analysisEjb.addReferenceSequence("Brucella_suis_ATCC_23445", "0", true);
        analysisEjb.addReferenceSequence("Brugia_malayi", "0", true);
        analysisEjb.addReferenceSequence("Burkholderia_thailandensis_454_TIGR", "-1", false);
        analysisEjb.addReferenceSequence("Burkholderia_thailandensis_454_TIGR", "0", true);
        analysisEjb.addReferenceSequence("Burkholderia_thailandensis_E264", "-1", false);
        analysisEjb.addReferenceSequence("Burkholderia_thailandensis_E264", "0", true);
        analysisEjb.addReferenceSequence("Burkholderia_thailandensis_E264", "-2", false);
        analysisEjb.addReferenceSequence("Caenorhabditis_elegans", "-1", false);
        analysisEjb.addReferenceSequence("Caenorhabditis_elegans", "0", false);
        analysisEjb.addReferenceSequence("Caenorhabditis_elegans", "1", true);
        analysisEjb.addReferenceSequence("Caenorhabditis_elegans_assembly_WS183", "0", true);
        analysisEjb.addReferenceSequence("Campylobacter_concisus_13826", "0", true);
        analysisEjb.addReferenceSequence("Campylobacter_jejuni_NCTC11168", "-2", false);
        analysisEjb.addReferenceSequence("Campylobacter_jejuni_NCTC11168", "0", true);
        analysisEjb.addReferenceSequence("Campylobacter_jejuni_NCTC11168", "-1", false);
        analysisEjb.addReferenceSequence("Candida_albicans_SC5314", "0", false);
        analysisEjb.addReferenceSequence("Candida_albicans_SC5314", "1", true);
        analysisEjb.addReferenceSequence("Candida_albicans_WO-1", "0", true);
        analysisEjb.addReferenceSequence("Candida_glabrata_CBS138", "0", true);
        analysisEjb.addReferenceSequence("Canis_lupus_familiaris", "0", true);
        analysisEjb.addReferenceSequence("Canis_lupus_familiaris_assembly2", "0", true);
        analysisEjb.addReferenceSequence("Canis_lupus_familiaris_assembly3", "0", true);
        analysisEjb.addReferenceSequence("Capsaspora_owczarzaki_ATCC_30864_with_mitochondria", "1", true);
        analysisEjb.addReferenceSequence("Capsaspora_owczarzaki_ATCC_30864_with_mitochondria", "0", false);
        analysisEjb.addReferenceSequence("Catenibacterium_mitsuokai_DSM_15897", "0", true);
        analysisEjb.addReferenceSequence("Caulobacter_crescentus_CB15", "0", true);
        analysisEjb.addReferenceSequence("Cavia_porcellus", "0", true);
        analysisEjb.addReferenceSequence("Citrobacter_koseri_ATCC_BAA-895", "0", true);
        analysisEjb.addReferenceSequence("Citrobacter_sp_30_2", "0", true);
        analysisEjb.addReferenceSequence("Clostridium_bartlettii_DSM_16795", "0", true);
        analysisEjb.addReferenceSequence("Clostridium_bolteae", "0", true);
        analysisEjb.addReferenceSequence("Clostridium_bolteae_ATCC_BAA-613", "0", true);
        analysisEjb.addReferenceSequence("Clostridium_hylemonae_DSM_15053", "0", true);
        analysisEjb.addReferenceSequence("Clostridium_perfringens_ATCC_13124", "0", true);
        analysisEjb.addReferenceSequence("Clostridium_ramosum_DSM_1402", "0", true);
        analysisEjb.addReferenceSequence("Clostridium_sp_M62", "0", true);
        analysisEjb.addReferenceSequence("Clostridium_sp_SS2_1", "0", true);
        analysisEjb.addReferenceSequence("Colletotrichum_graminicola_M1.001", "0", true);
        analysisEjb.addReferenceSequence("Collinsella_aerofaciens_ATCC_25986", "0", true);
        analysisEjb.addReferenceSequence("Coprobacillus_sp_D6", "0", false);
        analysisEjb.addReferenceSequence("Coprobacillus_sp_D6", "1", true);
        analysisEjb.addReferenceSequence("Coprococcus_comes_ATCC27758", "0", true);
        analysisEjb.addReferenceSequence("Corynebacterium_ulcerans_809", "0", true);
        analysisEjb.addReferenceSequence("Cryptococcus_neoformans_grubii_h99", "0", true);
        analysisEjb.addReferenceSequence("Cyanophage_6501-1", "1", true);
        analysisEjb.addReferenceSequence("Cyanophage_6501-1", "0", false);
        analysisEjb.addReferenceSequence("Cyanophage_P-SS2", "-1", false);
        analysisEjb.addReferenceSequence("Cyanophage_P-SS2", "0", true);
        analysisEjb.addReferenceSequence("Cyanophage_P-SSM2", "-1", false);
        analysisEjb.addReferenceSequence("Cyanophage_P-SSM2", "0", true);
        analysisEjb.addReferenceSequence("Cyanophage_P-SSP7", "0", true);
        analysisEjb.addReferenceSequence("Cyanophage_P-SSP7", "-1", false);
        analysisEjb.addReferenceSequence("Danio_rerio", "0", false);
        analysisEjb.addReferenceSequence("Danio_rerio", "1", false);
        analysisEjb.addReferenceSequence("Danio_rerio", "2", true);
        analysisEjb.addReferenceSequence("Dasypus_novemcinctus", "0", true);
        analysisEjb.addReferenceSequence("Delftia_acidovorans_SPH-1", "0", true);
        analysisEjb.addReferenceSequence("Dengue_virus_2_Harris_replicon", "0", true);
        analysisEjb.addReferenceSequence("Dengue_virus_2_V1074", "0", true);
        analysisEjb.addReferenceSequence("Dengue_virus_type1", "0", true);
        analysisEjb.addReferenceSequence("Dengue_virus_type2", "0", true);
        analysisEjb.addReferenceSequence("Dengue_virus_type2_JamaicaN1409", "0", true);
        analysisEjb.addReferenceSequence("Dengue_virus_type2_JamaicaN1409", "-1", false);
        analysisEjb.addReferenceSequence("Dengue_virus_type3", "0", true);
        analysisEjb.addReferenceSequence("Dengue_virus_type3_D3_H_IMTSSA-SRI_2000_1266", "0", true);
        analysisEjb.addReferenceSequence("Dengue_virus_type4", "0", true);
        analysisEjb.addReferenceSequence("Desulfovibrio_desulfuricans_ATCC_27774", "0", true);
        analysisEjb.addReferenceSequence("Dorea_formicigenerans_ATCC_27755", "0", true);
        analysisEjb.addReferenceSequence("Dorea_longicatena_DSM_13814", "0", true);
        analysisEjb.addReferenceSequence("Drosophila_melanogaster_BDGP4_3.41", "-1", false);
        analysisEjb.addReferenceSequence("Drosophila_melanogaster_BDGP4_3.41", "0", true);
        analysisEjb.addReferenceSequence("Echinops_telfairi", "0", true);
        analysisEjb.addReferenceSequence("Eggerthella_lenta_DSM_2243", "0", true);
        analysisEjb.addReferenceSequence("Encephalitozoon_cuniculi_GB-M1", "0", true);
        analysisEjb.addReferenceSequence("Enterobacter_cloacae_subsp_cloacae_ATCC_13047", "0", true);
        analysisEjb.addReferenceSequence("Enterobacteria_phage_T7", "-1", false);
        analysisEjb.addReferenceSequence("Enterobacteria_phage_T7", "0", true);
        analysisEjb.addReferenceSequence("Enterococcus_casseliflavus_899205", "0", true);
        analysisEjb.addReferenceSequence("Enterococcus_faecalis_V583", "2", true);
        analysisEjb.addReferenceSequence("Enterococcus_faecalis_V583", "1", false);
        analysisEjb.addReferenceSequence("Enterococcus_faecalis_V583", "0", false);
        analysisEjb.addReferenceSequence("Enterococcus_faecium_C68", "1", false);
        analysisEjb.addReferenceSequence("Enterococcus_faecium_C68", "0", false);
        analysisEjb.addReferenceSequence("Enterococcus_faecium_C68", "2", true);
        analysisEjb.addReferenceSequence("Epstein_Barr_virus_B95-8", "0", true);
        analysisEjb.addReferenceSequence("Epstein_Barr_virus_B95-8", "-1", false);
        analysisEjb.addReferenceSequence("Equus_caballus", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_536", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_55989", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_ATCC_11303", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_B_str_REL606", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_CFT073", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_DH10B", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_HS", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_K-12_MG1655_prokaryotic_dev", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_DH10B", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_MG1655", "-1", false);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_MG1655", "2", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_MG1655", "1", false);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_MG1655", "0", false);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_MG1655_HaeIII", "-1", false);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_MG1655_HaeIII", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_MG1655_plasmid_F", "-1", false);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_MG1655_plasmid_F", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_MG1655_vector_V1_HaeIII", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_K12_MG1655_vector_V1_HaeIII", "-1", false);
        analysisEjb.addReferenceSequence("Escherichia_coli_O157_H7_EDL933", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_TY-2482", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_W3110", "0", true);
        analysisEjb.addReferenceSequence("Escherichia_coli_transcriptome", "0", true);
        analysisEjb.addReferenceSequence("Eubacterium_dolichum_DSM_3991", "0", true);
        analysisEjb.addReferenceSequence("Exophiala_dermatitidis", "0", true);
        analysisEjb.addReferenceSequence("Francisella_tularensis_SCHUS4", "1", true);
        analysisEjb.addReferenceSequence("Francisella_tularensis_SCHUS4", "0", false);
        analysisEjb.addReferenceSequence("Francisella_tularensis_SCHUS4", "-1", false);
        analysisEjb.addReferenceSequence("Francisella_tularensis_SCHUS4", "-2", false);
        analysisEjb.addReferenceSequence("Francisella_tularensis_holarctica_257", "0", true);
        analysisEjb.addReferenceSequence("Francisella_tularensis_holarctica_LVS", "0", true);
        analysisEjb.addReferenceSequence("Fusarium_oxysporum_lycopersici_4286", "0", true);
        analysisEjb.addReferenceSequence("Fusarium_oxysporum_lycopersici_4287", "0", true);
        analysisEjb.addReferenceSequence("Fusobacterium_nucleatum", "0", true);
        analysisEjb.addReferenceSequence("Fusobacterium_nucleatum_subsp_nucleatum_ATCC_25586", "0", true);
        analysisEjb.addReferenceSequence("Fusobacterium_sp_7-1", "0", true);
        analysisEjb.addReferenceSequence("Gaeumannomyces_graminis_var_tritici_R3-111a-1", "0", true);
        analysisEjb.addReferenceSequence("Gasterosteus_aculeatus", "3", true);
        analysisEjb.addReferenceSequence("Gasterosteus_aculeatus", "2", false);
        analysisEjb.addReferenceSequence("Gasterosteus_aculeatus", "1", false);
        analysisEjb.addReferenceSequence("Gasterosteus_aculeatus", "0", false);
        analysisEjb.addReferenceSequence("Gasterosteus_aculeatus", "-1", false);
        analysisEjb.addReferenceSequence("Gasterosteus_aculeatus_scaffold17_0_2Mb", "0", true);
        analysisEjb.addReferenceSequence("Gemella_haemolysans_ATCC_10379", "0", true);
        analysisEjb.addReferenceSequence("Geomyces_destructans_20631-21", "0", true);
        analysisEjb.addReferenceSequence("Gibberella_moniliformis_7600", "0", true);
        analysisEjb.addReferenceSequence("Gibberella_zeae_PH-1", "0", true);
        analysisEjb.addReferenceSequence("Haemophilus_influenzae_Rd_KW20", "0", true);
        analysisEjb.addReferenceSequence("Haplochromis_burtoni", "0", true);
        analysisEjb.addReferenceSequence("Helicobacter_hepaticus_ATC51449", "0", true);
        analysisEjb.addReferenceSequence("Helicobacter_pylori_26695", "0", true);
        analysisEjb.addReferenceSequence("Hepatitis_C_virus_1a_H77", "-1", true);
        analysisEjb.addReferenceSequence("Hepatitis_C_virus_1a_H77", "0", true);
        analysisEjb.addReferenceSequence("Hepatitis_C_virus_1b_HCVT140", "-1", false);
        analysisEjb.addReferenceSequence("Hepatitis_C_virus_1b_HCVT140", "0", true);
        analysisEjb.addReferenceSequence("Hepatitis_C_virus_4F", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_454qualSNP", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_7BACs", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_7BACs", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_Bad_Promoter_Fosmids", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_Crohns_PSP3206", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_ENCODE_assembly18_chr4", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_ENCODE_assembly18_chr4", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_HLA_A_B_C", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_Driver_Screen", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_Driver_Screen_2", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_batch1", "0", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_batch1", "1", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_batch1", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_batch2", "0", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_batch2", "1", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_batch3", "0", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_batch3", "1", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_batch4", "1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_batch4", "2", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORF_batch4", "0", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORFpilot_set1", "1", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORFpilot_set1", "0", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_ORFpilot_set2", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RNA", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RNA_NMonly", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RNA_NMonly_no_alternate_transcripts", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-10B17", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-10B17", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-142I20", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-142I20", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-142I20a", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-142I20a", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-17A19", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-17A19", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-21F16", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-21F16", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-413B19", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-413B19", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-413B19_on_assembly18", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-413B19_on_assembly18", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-530N7", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-530N7", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-530N7_on_assembly18", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-530N7_on_assembly18", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-537K8", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-537K8", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-572P18", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-572P18", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-579C11", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-579C11", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-579C11_on_assembly18", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-579C11_on_assembly18", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-589P10", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-589P10", "-2", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-589P10", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-589P10_on_assembly18", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-589P10_on_assembly18", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-637F16", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-637F16", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-758N17", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-758N17", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-78M2", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RP11-78M2", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI11-543P15", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI11-543P15", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI11-543P15_RP11-413B19_RP11-589P10", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI11-543P15_RP11-413B19_RP11-589P10", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI11-543P15_on_assembly18", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI11-543P15_on_assembly18", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI5-1063M23", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI5-1063M23", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI5-1063M23_RP11-579C11_RP11-530N7", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI5-1063M23_RP11-579C11_RP11-530N7", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI5-1063M23_on_assembly18", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_RPCI5-1063M23_on_assembly18", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_T2D_exons_only_round_1", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_T2D_loci1", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_T2D_long_range_pcr", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_TCGA_SNP_Indel_Amplicons", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_TSP_231amplicons_design2", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_TSP_384amplicons_design2", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_TSP_61_Redesign1", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_TSP_80_Raindance", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_TSP_978amplicons_design2", "-2", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_TSP_978amplicons_design2", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_TSP_978amplicons_design2", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_TSP_IntGene", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_VH3-23gene_partial", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_VH3-23gene_partial", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_assembly17", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_assembly17", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_assembly18", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_assembly18", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_assembly19", "1", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_assembly19", "0", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_chr9_ALS", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_chromosome15_gaps", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_chromosome15_gaps", "0", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_chromosome15_gaps", "1", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_chromosome18_build34", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_chromosome18_build34", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_hRPK.332_H_18", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_hRPK.332_H_18", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_hRPK.472_J_18", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_hRPK.472_J_18", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_rDNA_U13369", "-1", false);
        analysisEjb.addReferenceSequence("Homo_sapiens_rDNA_U13369", "0", true);
        analysisEjb.addReferenceSequence("Homo_sapiens_refseq_transcriptome", "0", true);
        analysisEjb.addReferenceSequence("Human_herpesvirus_1", "0", true);
        analysisEjb.addReferenceSequence("Human_herpesvirus_2", "0", true);
        analysisEjb.addReferenceSequence("Human_immunodeficiency_virus_1", "0", false);
        analysisEjb.addReferenceSequence("Human_immunodeficiency_virus_1", "-1", false);
        analysisEjb.addReferenceSequence("Human_immunodeficiency_virus_1", "1", true);
        analysisEjb.addReferenceSequence("Klebsiella_oxytoca", "0", true);
        analysisEjb.addReferenceSequence("Klebsiella_oxytoca_KCTC_1686", "0", true);
        analysisEjb.addReferenceSequence("Klebsiella_pneumoniae_342", "0", true);
        analysisEjb.addReferenceSequence("Klebsiella_pneumoniae_subsp_pneumoniae_MGH_78578", "0", true);
        analysisEjb.addReferenceSequence("Klebsiella_pneumoniae_subsp_pneumoniae_MGH_78578_plasmids", "0", true);
        analysisEjb.addReferenceSequence("Kluyveromyces_lactis_CLIB210", "0", true);
        analysisEjb.addReferenceSequence("Lactobacillus_acidophilus_NCFM", "0", true);
        analysisEjb.addReferenceSequence("Lactobacillus_johnsonii_NCC533", "0", true);
        analysisEjb.addReferenceSequence("Lactobacillus_sakei_subsp_sakei_23K", "0", true);
        analysisEjb.addReferenceSequence("Lassa_virus", "0", true);
        analysisEjb.addReferenceSequence("Lassa_virus_strainNig08-04", "0", true);
        analysisEjb.addReferenceSequence("Lassa_virus_strainNig2010H", "0", true);
        analysisEjb.addReferenceSequence("Latimeria_chalumnae", "0", true);
        analysisEjb.addReferenceSequence("Latimeria_menadoensis", "0", true);
        analysisEjb.addReferenceSequence("Lepisosteus_oculatus", "0", true);
        analysisEjb.addReferenceSequence("Listeria_monocytogenes_4b_F2365", "-1", false);
        analysisEjb.addReferenceSequence("Listeria_monocytogenes_4b_F2365", "0", true);
        analysisEjb.addReferenceSequence("Listeria_monocytogenes_EGD-e", "0", true);
        analysisEjb.addReferenceSequence("Listeria_monocytogenes_EGD-e", "-1", false);
        analysisEjb.addReferenceSequence("Loa_loa", "0", true);
        analysisEjb.addReferenceSequence("Loxodonta_africana", "0", false);
        analysisEjb.addReferenceSequence("Loxodonta_africana", "1", false);
        analysisEjb.addReferenceSequence("Loxodonta_africana", "2", false);
        analysisEjb.addReferenceSequence("Loxodonta_africana", "3", true);
        analysisEjb.addReferenceSequence("Macaca_mulatta", "0", true);
        analysisEjb.addReferenceSequence("Magnaporthe_grisea_70-15", "-1", false);
        analysisEjb.addReferenceSequence("Magnaporthe_grisea_70-15", "1", true);
        analysisEjb.addReferenceSequence("Magnaporthe_grisea_70-15", "0", false);
        analysisEjb.addReferenceSequence("Magnaporthe_poae_atcc_64411", "0", false);
        analysisEjb.addReferenceSequence("Magnaporthe_poae_atcc_64411", "1", true);
        analysisEjb.addReferenceSequence("Methylobacterium_extorquens_AM1_mutant_plasmid_CM410_1_2_3", "0", false);
        analysisEjb.addReferenceSequence("Methylobacterium_extorquens_AM1_mutant_plasmid_CM410_1_2_3", "1", true);
        analysisEjb.addReferenceSequence("Methylobacterium_extorquens_AM1_plasmid_1_2_3", "0", true);
        analysisEjb.addReferenceSequence("Methylobacterium_extorquens_AM1_plasmid_CM410_1_2_3", "0", true);
        analysisEjb.addReferenceSequence("Metriaclima_zebra", "0", true);
        analysisEjb.addReferenceSequence("Microbotryum_violaceum", "0", true);
        analysisEjb.addReferenceSequence("Ministeria_vibrans_atcc_50519", "0", true);
        analysisEjb.addReferenceSequence("Mitsuokella_multacida_DSM_20544", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Enterococcus_faecalis_Escherichia_coli", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Enterococcus_faecalis_Escherichia_coli_Mycobacterium_tuberculosis", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Enterococcus_faecalis_Klebsiella_pneumoniae", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Escherichia_coli_HS_Staphylococcus_aureus_subsp_aureus_N315", "0", true);
        analysisEjb.addReferenceSequence("Mixed_HMP_649bacteria", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Microbiome_16SrRNA", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Mus_musculus_Francisella_tularensis_holarctica", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Pmarinus_Ecoli_Rsphaeroides", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Pmarinus_Ecoli_Rsphaeroides_plasmids_ABCDE", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Staphlococcus_aureus_N315_Klebsiella_pneumoniae_MGH_78578", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Staphylococcus_aureus_Rhodobacter_sphaeroides", "0", true);
        analysisEjb.addReferenceSequence("Mixed_Streptococcus_pyogenes_Proteus_mirabilis", "0", true);
        analysisEjb.addReferenceSequence("Mixed_eukaryotic_mock_community", "0", true);
        analysisEjb.addReferenceSequence("Mixed_plasmodium_ecoli_rhodo", "0", true);
        analysisEjb.addReferenceSequence("Mixed_spike_in_plasmids", "1", true);
        analysisEjb.addReferenceSequence("Mixed_spike_in_plasmids", "0", false);
        analysisEjb.addReferenceSequence("Mixed_yeast_8_genomes", "0", true);
        analysisEjb.addReferenceSequence("Monodelphis_domestica", "0", true);
        analysisEjb.addReferenceSequence("Monosiga_brevicollis", "0", true);
        analysisEjb.addReferenceSequence("Mortierella_verticillata_NRRL_6337_scaffolds", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_Cross_768amplicons_design1", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_RP23-478A9", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_RP24-211G11", "-2", false);
        analysisEjb.addReferenceSequence("Mus_musculus_RP24-211G11", "-1", false);
        analysisEjb.addReferenceSequence("Mus_musculus_RP24-211G11", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_RP24-211G11_vector_pTARBAC1_BamHI", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_RP24-211G11_vector_pTARBAC1_BamHI", "-1", false);
        analysisEjb.addReferenceSequence("Mus_musculus_RP24-211G11_vector_pTARBAC1_BamHI", "-2", false);
        analysisEjb.addReferenceSequence("Mus_musculus_RP24-342B2", "-1", false);
        analysisEjb.addReferenceSequence("Mus_musculus_RP24-342B2", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_RP24-368P9", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_RP24-368P9", "-1", false);
        analysisEjb.addReferenceSequence("Mus_musculus_RPCI-24-382M22", "-1", false);
        analysisEjb.addReferenceSequence("Mus_musculus_RPCI-24-382M22", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_assembly10", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_assembly5_CtoT.fw", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_assembly5_CtoT.fw", "-1", false);
        analysisEjb.addReferenceSequence("Mus_musculus_assembly5_CtoT.rc", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_assembly5_CtoT.rc", "-1", false);
        analysisEjb.addReferenceSequence("Mus_musculus_assembly8", "0", true);
        analysisEjb.addReferenceSequence("Mus_musculus_assembly8", "-1", false);
        analysisEjb.addReferenceSequence("Mus_musculus_assembly9", "0", false);
        analysisEjb.addReferenceSequence("Mus_musculus_assembly9", "1", true);
        analysisEjb.addReferenceSequence("Mustela_putorius_furo", "1", false);
        analysisEjb.addReferenceSequence("Mustela_putorius_furo", "2", true);
        analysisEjb.addReferenceSequence("Mustela_putorius_furo", "0", false);
        analysisEjb.addReferenceSequence("Mycobacterium_smegmatis_MC2_155", "0", false);
        analysisEjb.addReferenceSequence("Mycobacterium_smegmatis_MC2_155", "1", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_1435", "1", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_1435", "0", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_1435_supercontigs", "0", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_4207", "0", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_4207", "1", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_4207_supercontigs", "0", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_605", "1", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_605", "0", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_605_supercontigs", "0", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_CDC1551", "-1", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_CDC1551", "0", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_Erdman_WHO", "0", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_F11", "-3", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_F11", "0", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_F11", "1", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_F11", "-2", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_F11", "-1", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_F11_artificial", "0", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_H37Rv", "-1", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_H37Rv", "0", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_H37Rv", "1", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_H37Rv", "3", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_H37Rv", "2", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_H37Rv_plasmid_pKatG", "1", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_H37Rv_plasmid_pKatG", "0", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_Haarlem", "1", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_Haarlem", "0", false);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_T85_supercontigs", "0", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_W148", "0", true);
        analysisEjb.addReferenceSequence("Mycobacterium_tuberculosis_spoligotyping", "0", true);
        analysisEjb.addReferenceSequence("Neisseria_gonorrhoeae_35_02", "0", true);
        analysisEjb.addReferenceSequence("Neisseria_gonorrhoeae_FA1090", "1", true);
        analysisEjb.addReferenceSequence("Neisseria_gonorrhoeae_FA1090", "0", false);
        analysisEjb.addReferenceSequence("Neisseria_gonorrhoeae_FA19", "0", true);
        analysisEjb.addReferenceSequence("Neisseria_gonorrhoeae_MS11", "0", false);
        analysisEjb.addReferenceSequence("Neisseria_gonorrhoeae_MS11", "1", true);
        analysisEjb.addReferenceSequence("Nematocida_parisii_ERTm1", "0", true);
        analysisEjb.addReferenceSequence("Nematocida_parisii_ERTm2", "0", true);
        analysisEjb.addReferenceSequence("Neolamprologus_brichardi", "0", true);
        analysisEjb.addReferenceSequence("Neurospora_crassa_74A", "-3", false);
        analysisEjb.addReferenceSequence("Neurospora_crassa_74A", "-2", false);
        analysisEjb.addReferenceSequence("Neurospora_crassa_74A", "-1", false);
        analysisEjb.addReferenceSequence("Neurospora_crassa_74A", "0", true);
        analysisEjb.addReferenceSequence("Oreochromis_niloticus", "0", false);
        analysisEjb.addReferenceSequence("Oreochromis_niloticus", "1", true);
        analysisEjb.addReferenceSequence("Oribacterium_sinus_F0268", "0", true);
        analysisEjb.addReferenceSequence("Oryctolagus_cuniculus", "1", false);
        analysisEjb.addReferenceSequence("Oryctolagus_cuniculus", "0", false);
        analysisEjb.addReferenceSequence("Oryctolagus_cuniculus", "2", true);
        analysisEjb.addReferenceSequence("Otolemur_garnettii_assembly1", "0", false);
        analysisEjb.addReferenceSequence("Otolemur_garnettii_assembly1", "1", true);
        analysisEjb.addReferenceSequence("Paenibacillus_sp_D14", "0", true);
        analysisEjb.addReferenceSequence("Paenibacillus_sp_JDR-2", "0", true);
        analysisEjb.addReferenceSequence("Parabacteroides_distasonis_ATCC_8503", "0", true);
        analysisEjb.addReferenceSequence("Paracoccidioides_brasiliensis_Pb03", "0", true);
        analysisEjb.addReferenceSequence("PhiX174", "0", true);
        analysisEjb.addReferenceSequence("PhiX174", "-1", false);
        analysisEjb.addReferenceSequence("Phytophthora_infestans", "0", false);
        analysisEjb.addReferenceSequence("Phytophthora_infestans", "1", true);
        analysisEjb.addReferenceSequence("Phytophthora_infestans", "-1", false);
        analysisEjb.addReferenceSequence("Phytophthora_infestans", "-2", false);
        analysisEjb.addReferenceSequence("Phytophthora_infestans_mitochondrial_assembly", "0", true);
        analysisEjb.addReferenceSequence("Phytophthora_infestans_trancriptome", "0", true);
        analysisEjb.addReferenceSequence("Phytophthora_parasitica_CJ01A1", "0", true);
        analysisEjb.addReferenceSequence("Phytophthora_parasitica_INRA-310", "0", true);
        analysisEjb.addReferenceSequence("Phytophthora_parasitica_P10297", "0", true);
        analysisEjb.addReferenceSequence("Phytophthora_parasitica_P1569", "0", true);
        analysisEjb.addReferenceSequence("Phytophthora_parasitica_P1976", "0", true);
        analysisEjb.addReferenceSequence("Pichia_pastoris_GS115", "0", true);
        analysisEjb.addReferenceSequence("Plasmodium_berghi", "0", true);
        analysisEjb.addReferenceSequence("Plasmodium_falciparum_3D7", "3", false);
        analysisEjb.addReferenceSequence("Plasmodium_falciparum_3D7", "4", true);
        analysisEjb.addReferenceSequence("Plasmodium_falciparum_3D7", "2", false);
        analysisEjb.addReferenceSequence("Plasmodium_falciparum_3D7", "1", false);
        analysisEjb.addReferenceSequence("Plasmodium_falciparum_3D7", "0", false);
        analysisEjb.addReferenceSequence("Plasmodium_falciparum_3D7", "-1", false);
        analysisEjb.addReferenceSequence("Plasmodium_falciparum_HB3", "0", true);
        analysisEjb.addReferenceSequence("Plasmodium_falciparum_HB3", "-1", false);
        analysisEjb.addReferenceSequence("Plasmodium_knowlesi_H", "0", true);
        analysisEjb.addReferenceSequence("Plasmodium_vivax_Salvador_I", "0", true);
        analysisEjb.addReferenceSequence("Plasmodium_yoelii", "0", true);
        analysisEjb.addReferenceSequence("Pneumocystis_murina", "1", true);
        analysisEjb.addReferenceSequence("Pneumocystis_murina", "0", false);
        analysisEjb.addReferenceSequence("Pneumocystis_murina", "-1", false);
        analysisEjb.addReferenceSequence("Populus_trichocarpa_masked", "0", true);
        analysisEjb.addReferenceSequence("Populus_trichocarpa_masked", "-1", false);
        analysisEjb.addReferenceSequence("Populus_trichocarpa_unmasked", "0", true);
        analysisEjb.addReferenceSequence("Populus_trichocarpa_unmasked", "-1", false);
        analysisEjb.addReferenceSequence("Porphyromonas_endodontalis_ATCC_35406", "0", true);
        analysisEjb.addReferenceSequence("Prevotella_disiens_FB035-09AN", "0", true);
        analysisEjb.addReferenceSequence("Prevotella_melaninogenica_ATCC_25845", "0", true);
        analysisEjb.addReferenceSequence("Prevotella_oris_F0302", "0", true);
        analysisEjb.addReferenceSequence("Prochlorococcus_marinus_MED4", "0", true);
        analysisEjb.addReferenceSequence("Propionibacterium_acnes_KPA171202", "0", true);
        analysisEjb.addReferenceSequence("Proterospongia_sp_ATCC_50818_1", "0", true);
        analysisEjb.addReferenceSequence("Proteus_mirabilis_ATCC_29906", "0", true);
        analysisEjb.addReferenceSequence("Pseudomonas_aeruginosa_PA14", "0", true);
        analysisEjb.addReferenceSequence("Pseudomonas_aeruginosa_PAO1", "0", false);
        analysisEjb.addReferenceSequence("Pseudomonas_aeruginosa_PAO1", "-1", false);
        analysisEjb.addReferenceSequence("Pseudomonas_aeruginosa_PAO1", "1", true);
        analysisEjb.addReferenceSequence("Puccinia_graminis_tritici_CRL75-36-700-3", "0", true);
        analysisEjb.addReferenceSequence("Puccinia_striiformis_tritici_PST-78", "0", true);
        analysisEjb.addReferenceSequence("Puccinia_triticina", "0", false);
        analysisEjb.addReferenceSequence("Puccinia_triticina", "1", true);
        analysisEjb.addReferenceSequence("Pundamilia_nyererei", "0", true);
        analysisEjb.addReferenceSequence("Ralstonia_solanacearum_GMI1000", "0", true);
        analysisEjb.addReferenceSequence("Rattus_norvegicus", "0", true);
        analysisEjb.addReferenceSequence("Respiratory_syncytial_virus_A", "0", true);
        analysisEjb.addReferenceSequence("Respiratory_syncytial_virus_B", "0", true);
        analysisEjb.addReferenceSequence("Rhodobacter_sphaeroides_2.4.1", "1", true);
        analysisEjb.addReferenceSequence("Rhodobacter_sphaeroides_2.4.1", "0", false);
        analysisEjb.addReferenceSequence("Rhodobacter_sphaeroides_2.4.1_plasmids_ABCDE", "1", false);
        analysisEjb.addReferenceSequence("Rhodobacter_sphaeroides_2.4.1_plasmids_ABCDE", "2", true);
        analysisEjb.addReferenceSequence("Rhodobacter_sphaeroides_2.4.1_plasmids_ABCDE", "0", false);
        analysisEjb.addReferenceSequence("Rhodobacter_sphaeroides_ATCC17025_plasmids_pRSPA12345", "0", true);
        analysisEjb.addReferenceSequence("Rhodobacter_sphaeroides_ATCC17029_plasmid_pRSPH01", "0", true);
        analysisEjb.addReferenceSequence("Ruminococcus_gnavus_ATCC29149", "0", true);
        analysisEjb.addReferenceSequence("Ruminococcus_obeum_ATCC_29174", "0", true);
        analysisEjb.addReferenceSequence("Ruminococcus_torques_ATCC_27756", "0", true);
        analysisEjb.addReferenceSequence("Saccharomyces_castellii_NRRL-Y12630", "1", true);
        analysisEjb.addReferenceSequence("Saccharomyces_castellii_NRRL-Y12630", "0", false);
        analysisEjb.addReferenceSequence("Saccharomyces_cerevisiae_RM11-1a", "0", true);
        analysisEjb.addReferenceSequence("Saccharomyces_cerevisiae_S288c", "-1", false);
        analysisEjb.addReferenceSequence("Saccharomyces_cerevisiae_S288c", "2", true);
        analysisEjb.addReferenceSequence("Saccharomyces_cerevisiae_S288c", "1", false);
        analysisEjb.addReferenceSequence("Saccharomyces_cerevisiae_S288c", "0", false);
        analysisEjb.addReferenceSequence("Saccharomyces_cerevisiae_S288c_nuclear", "0", false);
        analysisEjb.addReferenceSequence("Saccharomyces_cerevisiae_S288c_nuclear", "-1", false);
        analysisEjb.addReferenceSequence("Saccharomyces_cerevisiae_S288c_nuclear", "1", true);
        analysisEjb.addReferenceSequence("Saccharomyces_cerevisiae_w303", "0", true);
        analysisEjb.addReferenceSequence("Saimiri_boliviensis", "0", true);
        analysisEjb.addReferenceSequence("Saprolegnia_parasitica_CBS_223_65", "0", true);
        analysisEjb.addReferenceSequence("Schizosaccharomyces_japonicus_yFS275", "0", true);
        analysisEjb.addReferenceSequence("Schizosaccharomyces_octosporus", "0", true);
        analysisEjb.addReferenceSequence("Schizosaccharomyces_pombe_972h", "-1", false);
        analysisEjb.addReferenceSequence("Schizosaccharomyces_pombe_972h", "0", false);
        analysisEjb.addReferenceSequence("Schizosaccharomyces_pombe_972h", "-2", false);
        analysisEjb.addReferenceSequence("Schizosaccharomyces_pombe_972h", "1", true);
        analysisEjb.addReferenceSequence("Sclerotinia_sclerotiorum_ATCC_18683", "0", true);
        analysisEjb.addReferenceSequence("Screening.negative.Homo_sapiens_GRCh37.1_p5", "0", true);
        analysisEjb.addReferenceSequence("Screening.negative.Homo_sapiens_GRCh37.1_p5_gencode.v10_pc_transcripts", "0", true);
        analysisEjb.addReferenceSequence("Screening.positive.Human_immunodeficiency_virus_5isolates", "0", true);
        analysisEjb.addReferenceSequence("Screening.positive.Human_immunodeficiency_virus_964isolates", "0", true);
        analysisEjb.addReferenceSequence("Selenomonas_sputigena_ATCC_35185", "0", true);
        analysisEjb.addReferenceSequence("Simian_immunodeficiency_virus_SIVmac239", "0", true);
        analysisEjb.addReferenceSequence("Simian_immunodeficiency_virus_SIVsmE543", "0", true);
        analysisEjb.addReferenceSequence("SolexaBAC_plus_vector", "0", false);
        analysisEjb.addReferenceSequence("SolexaBAC_plus_vector", "1", true);
        analysisEjb.addReferenceSequence("SolexaBAC_plus_vector", "-3", false);
        analysisEjb.addReferenceSequence("SolexaBAC_plus_vector", "-1", false);
        analysisEjb.addReferenceSequence("SolexaBAC_plus_vector", "-2", false);
        analysisEjb.addReferenceSequence("Sorex_araneus", "0", true);
        analysisEjb.addReferenceSequence("Sphaeroforma_arctica", "0", true);
        analysisEjb.addReferenceSequence("Spizellomyces_punctatus_DAOM_BR117_with_mitochondria", "0", true);
        analysisEjb.addReferenceSequence("Staphylococcus_aureus_MRSA252", "0", true);
        analysisEjb.addReferenceSequence("Staphylococcus_aureus_USA300", "0", true);
        analysisEjb.addReferenceSequence("Staphylococcus_aureus_USA300_plasmid", "1", true);
        analysisEjb.addReferenceSequence("Staphylococcus_aureus_USA300_plasmid", "0", false);
        analysisEjb.addReferenceSequence("Staphylococcus_aureus_subsp_aureus_N315", "0", true);
        analysisEjb.addReferenceSequence("Streptococcus_infantarius_subsp_infantarius_ATCC_BAA-102", "0", true);
        analysisEjb.addReferenceSequence("Streptococcus_pyogenes_MGAS315", "1", true);
        analysisEjb.addReferenceSequence("Streptococcus_pyogenes_MGAS315", "0", false);
        analysisEjb.addReferenceSequence("Streptomyces_SPB74", "0", true);
        analysisEjb.addReferenceSequence("Streptomyces_coelicolor_A3_2", "0", false);
        analysisEjb.addReferenceSequence("Streptomyces_coelicolor_A3_2", "-1", false);
        analysisEjb.addReferenceSequence("Streptomyces_coelicolor_A3_2", "1", true);
        analysisEjb.addReferenceSequence("Streptomyces_ghanaenis_ATCC14672", "0", true);
        analysisEjb.addReferenceSequence("Streptomyces_pristinaespiralis_ATCC_25486", "0", true);
        analysisEjb.addReferenceSequence("Streptomyces_roseosporus_NRRL11379", "0", true);
        analysisEjb.addReferenceSequence("Subdoligranulum_variabile_DSM_15176", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_200bp_EcoRV", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_200bp_EcoRV", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_5A_10D2_wt", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_5B_10D1_mut", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_8Cloned_Monotemplates", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_8Cloned_Monotemplates", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_8Cloned_Monotemplates.rc", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_8Cloned_Monotemplates.rc", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_CMV3_10D1_3FLAG", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_CMV3_10D2_3FLAG", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_CMV4_10D1_HA", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_CMV4_10D2_HA", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_CMV5_10D1_V5", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_CMV5_10D2_V5", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_CMV8_10D1_notag", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_CMV8_10D2_notag", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_Mut_H_in_pJazz_AG100912", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_Mut_M_in_pJazz_AG113012", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_NIF_Lib1Batch1", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_Solexa_test_monotemplates", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_Solexa_test_monotemplates", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_Solexa_test_templates", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_Solexa_test_templates", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_WT_H_in_pJazz_AG100912", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_WT_M_in_pJazz_AG113012", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_cistron_r1k", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_conformation", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_conformation", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_hayward_5_6_7_11", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_hayward_5_6_7_11", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_hayward_5_6_7_11.monotemplate", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_hayward_5_6_7_11.monotemplate", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_homopolymer_nonredundant", "-2", false);
        analysisEjb.addReferenceSequence("Synthetic_homopolymer_nonredundant", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_homopolymer_nonredundant", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_internal_controls_set1", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_014768", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_014768", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_014769", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_014769", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_014770", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_014770", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_014771", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_014771", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_041807_TSP_pool1", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_041807_TSP_pool2", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_041807_s170gp_quartile0", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_041807_s170gp_quartile1", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_041807_s170gp_quartile2", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_oligos_AMADID_041807_s170gp_quartile3", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_primer_test_monotemplates", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_primer_test_monotemplates", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_primer_test_templates", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_primer_test_templates", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_sequences_David_Liu", "1", true);
        analysisEjb.addReferenceSequence("Synthetic_sequestration_monotemplate", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_sequestration_monotemplate", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_sequestration_template", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_sequestration_template", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_shRNA_TRCA90", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_six_primer_test_templates", "-2", false);
        analysisEjb.addReferenceSequence("Synthetic_six_primer_test_templates", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_six_primer_test_templates", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_tag11", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_tag11", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_tag4", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_tag4", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_tag4_monotemplate", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_tag4_monotemplate", "0", true);
        analysisEjb.addReferenceSequence("Synthetic_test_fragments", "-1", false);
        analysisEjb.addReferenceSequence("Synthetic_test_fragments", "0", true);
        analysisEjb.addReferenceSequence("Tetrahymena_thermophila", "0", true);
        analysisEjb.addReferenceSequence("Thecamonas_trahens_atcc_50062", "0", true);
        analysisEjb.addReferenceSequence("Thermus_thermophilus_HB27", "0", true);
        analysisEjb.addReferenceSequence("Thermus_thermophilus_HB27", "-1", false);
        analysisEjb.addReferenceSequence("Thermus_thermophilus_HB27_plasmid_pTT27", "0", true);
        analysisEjb.addReferenceSequence("Thermus_thermophilus_HB27_plasmid_pTT27", "-1", false);
        analysisEjb.addReferenceSequence("Toxoplasma_gondii_GT1", "0", true);
        analysisEjb.addReferenceSequence("Treponema_denticola_ATCC_35405", "0", false);
        analysisEjb.addReferenceSequence("Trichophyton_rubrum_cbs118892", "1", true);
        analysisEjb.addReferenceSequence("Trichophyton_rubrum_cbs118892", "0", true);
        analysisEjb.addReferenceSequence("Vanderwaltozyma_polyspora_DSM70294", "0", true);
        analysisEjb.addReferenceSequence("Vector_SacB_pOTWI", "-1", false);
        analysisEjb.addReferenceSequence("Vector_SacB_pOTWI", "0", true);
        analysisEjb.addReferenceSequence("Vector_pJAN", "0", true);
        analysisEjb.addReferenceSequence("Vector_pTARBAC1", "0", true);
        analysisEjb.addReferenceSequence("Vector_pTARBAC1", "-1", false);
        analysisEjb.addReferenceSequence("Vector_pUC19", "0", true);
        analysisEjb.addReferenceSequence("Veillonella_parvula_DSM_2008", "0", true);
        analysisEjb.addReferenceSequence("Vibrio_alginolyticus_12G01", "0", true);
        analysisEjb.addReferenceSequence("Vibrio_cholerae_N16961", "0", true);
        analysisEjb.addReferenceSequence("Vibrio_cholerae_N16961", "-1", false);
        analysisEjb.addReferenceSequence("Vibrio_cholerae_O395", "-1", false);
        analysisEjb.addReferenceSequence("Vibrio_cholerae_O395", "0", true);
        analysisEjb.addReferenceSequence("Vibrio_parahaemolyticus_RIMD_2210633", "0", true);
        analysisEjb.addReferenceSequence("Vibrio_splendidus_12B01", "0", true);
        analysisEjb.addReferenceSequence("Wangiella_dermatitidis", "0", true);
        analysisEjb.addReferenceSequence("Wangiella_dermatitidis_largecontigs", "0", true);
        analysisEjb.addReferenceSequence("West_Nile_virus_lineageI_NY99", "0", true);
        analysisEjb.addReferenceSequence("Yarrowia_lipolytica", "0", true);
        analysisEjb.addReferenceSequence("pMSCV_neo_Gateway_Homo_sapiens_STK33", "0", true);
        analysisEjb.addReferenceSequence("shRNA_EcoRI_LKOpool", "0", true);
        analysisEjb.addReferenceSequence("shRNA_XhoI_LKOpool_AA", "0", true);
        analysisEjb.addReferenceSequence("shRNA_XhoI_LKOpool_TT", "0", true);
    }

    /**
     * Performs some analysis type maintenance to go along with Illumina run query changes:
     *
     * 1. Clear analysis types from products when they will not be used due to not having workflow set
     * 2. Change products' analysis type from "Resequencing" to "HybridSelection.Resequencing"
     */
    @Test(enabled = false)
    public void gplim3900FixAnalysisTypes() {
        userBean.loginOSUser();
        String oldAnalysisType = "Resequencing";
        String newAnalysisType = "HybridSelection." + oldAnalysisType;

        AnalysisType analysisType = analysisTypeDao.findByBusinessKey(newAnalysisType);
        assertThat(analysisType, nullValue());

        /*
         * Calling into an EJB, this gets its own transaction and is therefore not saved along with the product updates
         * and FixupCommentary below. This shouldn't be a concern, though, because the audit trail will look the same as
         * if I had added the analysis type through the admin UI. The advantage to doing it here in the fixup is that it
         * prevents HybridSelection.Resequencing from being selected before deploying the code change to not prepend
         * "HybridSelection."
         */
        analysisEjb.addAnalysisType(newAnalysisType);

        List<Product> products = productDao.findAllWithAnalysisType();
        for (Product product : products) {
            if (product.getWorkflowName() == Workflow.NONE) { // small change when Workflow enum was removed
                product.setAnalysisTypeKey(null);
            } else {
                if (product.getAnalysisTypeKey().equals(oldAnalysisType)) {
                    product.setAnalysisTypeKey(newAnalysisType);
                }
            }
        }

        productDao.persist(new FixupCommentary("GPLIM-3900 Update products to use real analysis types"));
    }
}
