-- GPLIM-6069 Add event operator
ALTER TABLE MERCURYDW.IM_EVENT_FACT
    ADD OPERATOR VARCHAR2(32);
ALTER TABLE MERCURYDW.EVENT_FACT
    ADD OPERATOR VARCHAR2(32);

CREATE TABLE MERCURYDW.IM_EVENT_METADATA
(
    LINE_NUMBER   NUMBER(9, 0),
    ETL_DATE      DATE,
    IS_DELETE     CHAR,
    METADATA_ID   NUMBER(19, 0),
    LAB_EVENT_ID  NUMBER(19, 0),
    METADATA_TYPE VARCHAR2(32),
    VALUE         VARCHAR2(255)
);

CREATE TABLE MERCURYDW.EVENT_METADATA
(
    METADATA_ID   NUMBER(19, 0) NOT NULL,
    LAB_EVENT_ID  NUMBER(19, 0) NOT NULL,
    METADATA_TYPE VARCHAR2(32)  NOT NULL,
    VALUE         VARCHAR2(255),
    ETL_DATE      DATE          NOT NULL
);

CREATE INDEX IDX_EVENT_METADATA
    ON MERCURYDW.EVENT_METADATA (METADATA_ID);
