-- --------------------------------
-- https://gpinfojira.broadinstitute.org/jira/browse/GPLIM-5675
-- Flowcell designation refactor
-- --------------------------------

ALTER TABLE MERCURYDW.FLOWCELL_DESIGNATION
  ADD BATCH_STARTING_VESSEL_ID NUMBER(19,0);

ALTER TABLE MERCURYDW.FLOWCELL_DESIGNATION
  ADD LOADING_VESSEL VARCHAR2(48);

ALTER TABLE MERCURYDW.FLOWCELL_DESIGNATION
  DROP COLUMN FCLOAD_ETL_DATE;

ALTER TABLE MERCURYDW.FLOWCELL_DESIGNATION
  MODIFY DESIGNATION_ID NULL;

ALTER TABLE MERCURYDW.FLOWCELL_DESIGNATION
  DROP CONSTRAINT PK_FLOWCELL_DESIGNATION;

DROP INDEX PK_FLOWCELL_DESIGNATION;

CREATE INDEX PK_FCT_BATCH_VESSEL
  ON MERCURYDW.FLOWCELL_DESIGNATION(BATCH_STARTING_VESSEL_ID);

-- Column name DESIGNATION_ID was a misnomer for BATCH_STARTING_VESSEL_ID
UPDATE MERCURYDW.FLOWCELL_DESIGNATION
SET BATCH_STARTING_VESSEL_ID = DESIGNATION_ID;
UPDATE MERCURYDW.FLOWCELL_DESIGNATION
SET DESIGNATION_ID = NULL;
COMMIT;

ALTER TABLE MERCURYDW.FLOWCELL_DESIGNATION
  ADD CONSTRAINT PK_FCT_BATCH_VESSEL PRIMARY KEY ( BATCH_STARTING_VESSEL_ID ) USING INDEX PK_FCT_BATCH_VESSEL;

DROP TABLE  MERCURYDW.IM_FCT_CREATE;
DROP TABLE  MERCURYDW.IM_FCT_LOAD;

CREATE TABLE  MERCURYDW.IM_FCT_CREATE(
  LINE_NUMBER NUMBER(9,0) NOT NULL,
  ETL_DATE DATE NOT NULL,
  IS_DELETE CHAR NOT NULL,
  BATCH_STARTING_VESSEL_ID NUMBER(19,0),
  DESIGNATION_ID NUMBER(19,0) NULL,
  FCT_ID NUMBER(19,0),
  FCT_NAME VARCHAR2(48),
  FCT_TYPE VARCHAR2(8),
  DESIGNATION_LIBRARY VARCHAR2(48),
  LOADING_VESSEL VARCHAR2(48),
  CREATION_DATE DATE,
  FLOWCELL_TYPE VARCHAR2(48),
  LANE VARCHAR2(32),
  CONCENTRATION NUMBER(19,2),
  IS_POOL_TEST CHAR
);

CREATE TABLE  MERCURYDW.IM_FCT_LOAD(
  LINE_NUMBER NUMBER(9,0) NOT NULL,
  ETL_DATE DATE NOT NULL,
  IS_DELETE CHAR NOT NULL,
  BATCH_STARTING_VESSEL_ID NUMBER(19,0),
  FLOWCELL_BARCODE VARCHAR2(48)
);
