-- USER SQL
CREATE USER mercury IDENTIFIED BY mercury_dev1
DEFAULT TABLESPACE "SQUID_NEW_DATA"
TEMPORARY TABLESPACE "TEMP";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE SEQUENCE TO mercury ;
GRANT CREATE TABLE TO mercury ;
GRANT CREATE SESSION TO mercury ;
GRANT SELECT ANY DICTIONARY TO mercury ;

-- QUOTAS
ALTER USER mercury QUOTA UNLIMITED ON SQUID_NEW_DATA;
